"use client";

/**
 * The one client-only wrapper. `'use client'` must be line 1 of this file:
 * PrivyProvider is a third-party React context that mounts dialogs and iframes,
 * so importing it from a server component is the classic App Router failure
 * ("createContext is not a function" / "window is not defined"). Ported from
 * the Nuvem dashboard's src/app/providers.tsx (HEAD fd927b0), EVM only.
 *
 * It also carries the runtime configuration down to the rest of the tree. The
 * server read `process.env` per request and passed the result as a prop, so no
 * `NEXT_PUBLIC_*` value had to be baked into the bundle at build time — which is
 * what keeps one Docker image usable on both a VPS and Railway.
 *
 * What arrives here is PublicConfig, never ServerConfig: the privileged RPC URL
 * stays on the server. The `walletRpcUrl` below is what the wallet is given for
 * chain 4663, and no page read uses it.
 */

import { PrivyProvider } from "@privy-io/react-auth";
import { createContext, useContext, useMemo } from "react";

import { robinhoodChain } from "@/lib/chain";
import type { PublicConfig } from "@/lib/config";

const ConfigContext = createContext<PublicConfig | null>(null);

export function useConfig(): PublicConfig {
  const config = useContext(ConfigContext);
  if (config === null) {
    throw new Error("useConfig() was called outside <Providers>. Wrap the component in it.");
  }
  return config;
}

export function Providers({ config, children }: { config: PublicConfig; children: React.ReactNode }) {
  const chain = useMemo(() => robinhoodChain(config.walletRpcUrl, config.explorerUrl), [config.walletRpcUrl, config.explorerUrl]);

  return (
    <ConfigContext.Provider value={config}>
      <PrivyProvider
        appId={config.privyAppId}
        {...(config.privyClientId ? { clientId: config.privyClientId } : {})}
        config={{
          // Chain 4663 is absent from viem/chains and from Privy's built-in
          // list. Passing a defineChain object here is the documented path.
          // supportedChains must be non-empty AND contain defaultChain, or
          // PrivyProvider throws at construction — with one custom chain, the
          // same object goes in both.
          defaultChain: chain,
          supportedChains: [chain],

          // The PENSION KEY signs in with an external EOA: it holds the
          // withdrawal key for every saving in the vault, and an
          // email-recoverable custody model is the wrong place for that.
          //
          // A TRADING wallet is the opposite case. It is generated on demand,
          // the user owns it, losing it costs trading capital rather than
          // savings, and being fresh is a feature — the worker only attests
          // what it has observed, so a wallet with no history has nothing it
          // cannot account for. Creation stays MANUAL ('off' on login) so an
          // address is minted only when someone asks for one, and minted
          // born-seated (WEB_WALLETS.md §0.5) rather than by a login hook
          // that cannot attach a signer.
          loginMethods: ["wallet"],
          embeddedWallets: {
            ethereum: { createOnLogin: "off" },
          },

          appearance: {
            // THE TRUST STATEMENT LIVES ON THE MODAL, NOT IN THE SIGNED
            // MESSAGE. The SIWE body is generated by Privy's server and must
            // stay the standard shape — wallets treat marketing text inside a
            // signature request as a phishing signal, which is the opposite of
            // reassurance. What we CAN say, we say here, where the user
            // decides whether to connect.
            landingHeader: "Connect your pension key",
            loginMessage:
              "SIP is permissionless. Only your pension key can withdraw — the team has no access to your funds.",
            // EVM only. Phantom is also a Solana wallet and, offered through the
            // ethereum path, it starts SIWE against a Solana account and dies
            // with "There was an error attempting to sign the transaction";
            // filtering the modal to ethereum keeps that path closed.
            walletChainType: "ethereum-only",
            // ORDER IS THE PRODUCT DECISION HERE: the wallets our users
            // actually trade with come first. Privy deprecated the explicit
            // `rabby_wallet` entry, so Rabby arrives via
            // `detected_ethereum_wallets` in FIRST position; MetaMask being
            // listed explicitly below pulls it OUT of that detected group,
            // which leaves the group ≈ Rabby (plus any other EVM extension
            // the browser carries). Note detected_ethereum_wallets does not
            // work in mobile browsers.
            walletList: ["detected_ethereum_wallets", "metamask"],
          },
        }}
      >
        {children}
      </PrivyProvider>
    </ConfigContext.Provider>
  );
}

export default Providers;
