#!/usr/bin/env bash
# THE JUPITER GUARD PROOF, one command:
#
#   ./scripts/jupiter-fork.sh [--slippage <bps>] [--dexes <label,...>]
#                             [--exclude <label,...>]
#
# The flags are passed straight to phase 1 and pin the experiment: the
# gross-versus-net question is about the AMM that makes the final transfer, so
# a run that is about a gross-quoting venue has to name it. Measured
# 2026-09-20: `--dexes Manifest --slippage 50` puts this harness on a one-hop
# gross-quoting route with the slippage at the mint's local fee.
#
# --dexes AND --exclude ARE MUTUALLY EXCLUSIVE, and the default exclusion is
# skipped whenever a venue is pinned. Jupiter's quote endpoint refuses the two
# lists together — HTTP 400, "Cannot set dexes and exclude dexes at the same
# time" — so a default that applied to pinned runs as well, as one did briefly,
# made the measured command above unrunnable. Phase 1 now refuses the pair
# itself, with that reason.
#
# A PIN IS A REQUEST THE MARKET MAY REFUSE, and re-running this proof has to
# expect that. Later the same day, `--dexes Manifest --slippage 50` answered
# {"error":"No routes found"}: Manifest no longer carried a direct
# USDC -> FIGUREAI leg, while the unpinned quote routed through Raydium CLMM
# (a NET-quoting venue) as it always had. That is the file's own claim about
# the basis coming true — the venue belongs to the moment, not to the mint —
# and not a broken harness. To retake a GROSS measurement, pin whatever venue
# quotes gross for that pair at that hour; jupiter-sim.ts prints the basis per
# row, which is how to find one.
#
# RE-RUN THE SAME DAY WITH DEFAULT FLAGS (`./scripts/jupiter-fork.sh`: slippage
# 200, nothing pinned, Hadron excluded) — 8/8 cases as expected, one hop
# through Raydium CLMM: quoted out 27,409,402, venue threshold 26,861,214,
# local fee 50 bps (the cloned validator starts at epoch 0), CREDIT 27,547,833,
# withheld 138,432, safe min_out 26,726,907, margin 820,926. That venue quotes
# NET — the gross delivered, taken net of mainnet's 100 bps, is the quote to
# the raw unit — so this run exercises every guard but not the gross-quoting
# revert, which needs a gross venue to be both pinned and available.
#
# Buys real FIGUREAI (Token-2022, transfer fee) with the vault's USDC through a
# REAL Jupiter sharedAccountsRoute, against mainnet state cloned into a local
# validator, driven by invest() — and measures what jupiter-sim.ts could not:
# that the delta OUR PROGRAM records is the NET credit, and WHICH guard each
# candidate min_out actually runs into. Measured, a min_out taken from the
# quote's outAmount on a gross-quoting venue is the one that reverts with
# FillTooSmall 6020; one taken from otherAmountThreshold does not, and when the
# credit does fall under that threshold it is JUPITER that refuses first, with
# 0x1771 inside the CPI (this script then exits 2 and says so).
#
# No mainnet transaction is ever sent. The only keys involved are two local
# test identities generated by phase 1 and funded by local airdrop.
set -euo pipefail
cd "$(dirname "$0")/.."
RPC="${MAINNET_RPC:-https://api.mainnet-beta.solana.com}"
LOCAL_RPC="http://127.0.0.1:8899"
LOG=/tmp/jupiter-fork-validator.log

command -v solana-test-validator >/dev/null || { echo "solana-test-validator not on PATH" >&2; exit 1; }
[ -f target/deploy/sip_vault.so ] || { echo "target/deploy/sip_vault.so is missing: run anchor build first" >&2; exit 1; }

echo "── phase 1: quote a single-hop route on mainnet and work out what to clone ──"
npx tsx scripts/jupiter-fork-setup.ts "$@"

PROGRAM=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("target/idl/sip_vault.json")).address)')
ADMIN=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("scripts/.local/jupiter-route.json")).admin)')
USDC_ACCT=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("scripts/.local/jupiter-vault-usdc.json")).pubkey)')

CLONE_ARGS=()
while IFS= read -r a; do [ -n "$a" ] && CLONE_ARGS+=(--clone "$a"); done < scripts/.local/jupiter-clones.txt
while IFS= read -r p; do [ -n "$p" ] && CLONE_ARGS+=(--clone-upgradeable-program "$p"); done < scripts/.local/jupiter-programs.txt

echo "── phase 2: start validator (cloning $(( ${#CLONE_ARGS[@]} / 2 )) mainnet entries) ──"
pkill -f solana-test-validator 2>/dev/null || true
sleep 2
rm -rf test-ledger
# --upgradeable-program, not `anchor deploy`: it puts sip_vault at its real
# mainnet address WITH a ProgramData account whose upgrade authority is the
# local admin, which is exactly what init_config checks — and it needs no
# program keypair on disk.
solana-test-validator --reset --quiet \
  --url "$RPC" \
  --upgradeable-program "$PROGRAM" target/deploy/sip_vault.so "$ADMIN" \
  "${CLONE_ARGS[@]}" \
  --account "$USDC_ACCT" scripts/.local/jupiter-vault-usdc.json \
  > "$LOG" 2>&1 &
VALIDATOR=$!
trap 'kill $VALIDATOR 2>/dev/null || true' EXIT

for i in $(seq 1 60); do
  if solana cluster-version -u "$LOCAL_RPC" >/dev/null 2>&1; then break; fi
  if ! kill -0 $VALIDATOR 2>/dev/null; then echo "validator died; see $LOG" >&2; tail -30 "$LOG" >&2; exit 1; fi
  sleep 1
done
solana cluster-version -u "$LOCAL_RPC" >/dev/null 2>&1 || { echo "validator never came up; see $LOG" >&2; tail -30 "$LOG" >&2; exit 1; }
echo "   validator up"

echo "── phase 3: the guards, on the cloned route ──"
npx tsx scripts/jupiter-fork-test.ts
