// Phase 3 of the JUPITER fork proof: run sip_vault's invest() through a REAL
// Jupiter sharedAccountsRoute against cloned mainnet state, and answer the one
// question jupiter-sim.ts structurally could not.
//
// WHAT THIS PROVES THAT THE MAINNET SIMULATION DID NOT. jupiter-sim.ts measured
// what Jupiter credits a destination account, with the authority slot marked a
// signer in the OUTER instruction because there was no invest() to lend it.
// Here the authority IS a vault PDA that cannot sign anything, the signature is
// lent by invoke_signed from inside the deployed program's own bytes, and the
// number under test is the delta THE PROGRAM measures — not the one we read off
// the account ourselves.
//
// WHY THE INVESTS ARE SIMULATED AND NOT SENT. Simulation on the local validator
// executes the real program, the real CPI and the real token transfers, returns
// the real error codes, and hands back the post-state of any account asked for
// — everything this proof asserts. It also means no invest() in this file is
// ever signed, which keeps the rule "simulation only" true without weakening
// anything measured. Each case therefore runs from an IDENTICAL base state,
// which is stricter than chaining them would be.
//
// The SETUP (init_config, create_vault, the two ATAs, set_invest_policy) does
// send local transactions: there is no way to simulate a vault into existence.
// Those touch no venue and no funds, they are signed by throwaway identities
// generated by phase 1, and they exist only on 127.0.0.1.
//
// THE EPOCH TRAP, MEASURED HERE. A cloned validator starts at epoch 0, so
// Token-2022 applies the mint's OLDER transfer fee (50 bps) even though mainnet
// is past epoch 1039 and charging 100. Every number below is therefore computed
// from the fee THIS validator will actually apply, read from the cloned mint —
// which is exactly why jupiter-route.ts reads the rate instead of hardcoding it.

import * as anchor from "@coral-xyz/anchor";
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  TransactionInstruction,
  TransactionMessage,
  VersionedTransaction,
  ComputeBudgetProgram,
  type SimulatedTransactionAccountInfo,
} from "@solana/web3.js";
import {
  NATIVE_MINT,
  TOKEN_2022_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  createAssociatedTokenAccountIdempotent,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  netOfTransferFee,
  readDestinationTransferFee,
  transferFeeOn,
  type TransferFeeRate,
} from "./jupiter-route";

const LOCAL = join(__dirname, ".local");
const RPC = "http://127.0.0.1:8899";
const BPF_LOADER_UPGRADEABLE = new PublicKey("BPFLoaderUpgradeab1e11111111111111111111111");
const USDC = new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v");

/** Anchor error codes this proof asserts on, from idl/sip_vault.json. */
const ERR = { WrongVenue: 6015, FloorTooLow: 6019, FillTooSmall: 6020, Overspent: 6021, DisallowedVaultAccount: 6034 };

interface RouteFile {
  readonly target: { readonly name: string; readonly mint: string };
  /** What phase 1 ASKED FOR. This, and never the route's own number, is amount_in. */
  readonly requestedAmountIn: string;
  /** What the route's bytes carry. Recorded to be compared, not to be spent. */
  readonly instructionInAmount: string;
  readonly hops: number;
  readonly labels: readonly string[];
  readonly venueProgram: string;
  readonly venueData: string;
  readonly remainingAccounts: readonly { readonly pubkey: string; readonly isSigner: boolean; readonly isWritable: boolean }[];
  readonly quotedOut: string;
  readonly venueThreshold: string;
  readonly mainnetTransferFeeBps: number;
  readonly vault: string;
  readonly vaultIn: string;
  readonly vaultTarget: string;
}

function identity(name: string): Keypair {
  return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(join(LOCAL, name), "utf8"))));
}

/**
 * A token account's amount and, for Token-2022, the fee withheld inside it.
 *
 * The withheld field is what makes the decomposition exact rather than
 * inferred: the destination ATA is created empty in this same run, so
 * pre-amount and pre-withheld are both zero and
 *   gross delivered = credit + withheld
 * is arithmetic, not a hypothesis.
 */
function decodeTokenAccount(address: PublicKey, account: SimulatedTransactionAccountInfo | null): {
  readonly amount: bigint;
  readonly withheld: bigint;
} {
  // A null post-state is the simulator declining to tell us the balance.
  // Returning zero here would read as "the route credited nothing", which is
  // the exact wrong answer to the exact question this file asks.
  if (account === null) throw new Error(`the simulator returned no post-state for ${address.toBase58()}`);
  const data = Buffer.from(account.data[0]!, "base64");
  if (data.length < 165) throw new Error(`post-state for ${address.toBase58()} is ${data.length} bytes, not a token account`);
  const amount = data.readBigUInt64LE(64);
  // Token-2022 extensions start at 165: [account_type u8][type u16][len u16][data].
  // TransferFeeAmount is type 2 and carries a single u64 of withheld fee.
  let withheld = 0n;
  let cursor = 166;
  while (cursor + 4 <= data.length) {
    const type = data.readUInt16LE(cursor);
    const len = data.readUInt16LE(cursor + 2);
    if (type === 2 && cursor + 4 + 8 <= data.length) withheld = data.readBigUInt64LE(cursor + 4);
    cursor += 4 + len;
  }
  return { amount, withheld };
}

interface Case {
  readonly name: string;
  readonly minOut: bigint;
  readonly extraAccount?: PublicKey;
  readonly venueProgramOverride?: PublicKey;
  readonly expect: "ok" | number;
  readonly why: string;
}

async function main(): Promise<void> {
  const route = JSON.parse(readFileSync(join(LOCAL, "jupiter-route.json"), "utf8")) as RouteFile;
  const idl = JSON.parse(readFileSync(join(__dirname, "../target/idl/sip_vault.json"), "utf8"));
  const connection = new Connection(RPC, "confirmed");

  const admin = identity("jupiter-fork-admin.json");
  const owner = identity("jupiter-fork-owner.json");
  // The vault's OWNER cranks. invest() admits the owner or the config's
  // keeper and nobody else (NuvemError::UnauthorizedCrank), which this run
  // confirmed the hard way before the crank was changed to a permitted key.
  const crank = owner;
  const provider = new anchor.AnchorProvider(connection, new anchor.Wallet(admin), { commitment: "confirmed" });
  anchor.setProvider(provider);
  const program = new anchor.Program(idl, provider);
  const programId = program.programId;

  for (const who of [admin.publicKey, owner.publicKey]) {
    await connection.confirmTransaction(await connection.requestAirdrop(who, 5e9), "confirmed");
  }

  const vault = new PublicKey(route.vault);
  const vaultIn = new PublicKey(route.vaultIn);
  const vaultTarget = new PublicKey(route.vaultTarget);
  const targetMint = new PublicKey(route.target.mint);
  const venueProgram = new PublicKey(route.venueProgram);
  // AMOUNT_IN IS OURS. invest() only refuses a spend ABOVE amount_in, so a
  // number taken from the route would be a ceiling the API chose for the
  // vault's own money. Phase 1 already refused a route whose bytes disagreed
  // with the request; this asserts the artifact on disk still does.
  const amountIn = BigInt(route.requestedAmountIn);
  if (BigInt(route.instructionInAmount) !== amountIn) {
    throw new Error(
      `the captured route spends ${route.instructionInAmount} but ${amountIn} was requested; ` +
        "re-run jupiter-fork-setup.ts",
    );
  }
  const [configPda] = PublicKey.findProgramAddressSync([Buffer.from("config")], programId);
  const [policyPda] = PublicKey.findProgramAddressSync([Buffer.from("invest"), vault.toBuffer()], programId);
  const [programData] = PublicKey.findProgramAddressSync([programId.toBuffer()], BPF_LOADER_UPGRADEABLE);

  console.log(`\nroute: ${route.hops} hop [${route.labels.join(" -> ")}] — 5 USDC -> ${route.target.name}`);
  console.log(`program: ${programId.toBase58()}  vault: ${vault.toBase58()}`);

  // ── setup (local transactions; no venue, no funds) ──────────────────────
  // Idempotent: the proof is re-runnable against a validator that is already
  // set up, so an iteration costs a simulation and not a fresh mainnet clone.
  const exists = async (key: PublicKey): Promise<boolean> => (await connection.getAccountInfo(key, "confirmed")) !== null;
  if (!(await exists(configPda))) {
    await program.methods
      .initConfig(admin.publicKey)
      .accountsPartial({ authority: admin.publicKey, config: configPda, program: programId, programData, systemProgram: SystemProgram.programId })
      .rpc();
  }
  if (!(await exists(vault))) {
    await program.methods
      .createVaultV2(0, 2_000, 20, new anchor.BN(1_000_000_000), new anchor.BN(0))
      .accountsPartial({ owner: owner.publicKey, systemProgram: SystemProgram.programId })
      .signers([owner])
      .rpc();
  }
  await createAssociatedTokenAccountIdempotent(connection, admin, targetMint, vault, undefined, TOKEN_2022_PROGRAM_ID, undefined, true);
  // The decoy for guard (1): a THIRD vault-owned token account, which the
  // deltas do not measure and the route therefore may not mention.
  const vaultWsol = await createAssociatedTokenAccountIdempotent(connection, admin, NATIVE_MINT, vault, undefined, TOKEN_PROGRAM_ID, undefined, true);

  // ── the numbers, from the fee THIS validator applies ────────────────────
  const fee = await readDestinationTransferFee(connection, targetMint);
  const local: TransferFeeRate = fee.current;
  const quotedOut = BigInt(route.quotedOut);
  const threshold = BigInt(route.venueThreshold);
  const safeMinOut = netOfTransferFee(threshold, local);

  console.log(`\nfee:  local epoch ${fee.epoch} -> ${local.basisPoints} bps   (mainnet quoted under ${route.mainnetTransferFeeBps} bps)`);
  console.log(`      quoted out ${quotedOut}   venue threshold ${threshold}   safe min_out ${safeMinOut}`);

  const legs = (rateWad: bigint) => [{ mint: targetMint, weightBps: 10_000, minOutRateWad: new anchor.BN(rateWad.toString()) }];
  const setPolicy = async (rateWad: bigint): Promise<void> => {
    await program.methods
      .setInvestPolicy(
        legs(rateWad), venueProgram, USDC,
        new anchor.BN("30000000000000000"), new anchor.BN("1000000"), new anchor.BN("20000000"), new anchor.BN("60000000"), true,
      )
      .accountsPartial({ owner: owner.publicKey, vault, policy: policyPda, systemProgram: SystemProgram.programId })
      .signers([owner])
      .rpc();
  };
  // A floor stated in NET terms: 5.0 wad is under safeMinOut/amountIn (~5.41).
  const NET_FLOOR_WAD = 5_000_000_000_000_000_000n;
  // The same floor stated in GROSS terms — taken from the venue's threshold as
  // if the vault were credited the gross. This is the corollary the other
  // session has to act on, and it is asserted as a case below.
  const GROSS_FLOOR_WAD = (threshold * 1_000_000_000_000_000_000n) / amountIn;
  // A deliberately slack floor for the measuring probe below. invest() refuses
  // min_out under the leg's own floor before it ever reaches the venue, so a
  // probe that wants to observe the RAW fill has to clear a floor it is not
  // trying to test.
  const PROBE_FLOOR_WAD = 1_000_000_000_000_000_000n;
  const probeMinOut = (amountIn * PROBE_FLOOR_WAD) / 1_000_000_000_000_000_000n;
  await setPolicy(PROBE_FLOOR_WAD);

  const baseMetas = route.remainingAccounts.map((meta) => ({
    pubkey: new PublicKey(meta.pubkey),
    isSigner: meta.isSigner,
    isWritable: meta.isWritable,
  }));

  const build = async (c: Case): Promise<VersionedTransaction> => {
    const metas = [...baseMetas];
    if (c.extraAccount !== undefined) metas.push({ pubkey: c.extraAccount, isSigner: false, isWritable: true });
    const ix: TransactionInstruction = await program.methods
      .invest(0, new anchor.BN(amountIn.toString()), new anchor.BN(c.minOut.toString()), Buffer.from(route.venueData, "base64"))
      .accountsPartial({
        crank: crank.publicKey, config: configPda, vault, policy: policyPda,
        vaultIn, vaultTarget, targetMint, venueProgram: c.venueProgramOverride ?? venueProgram,
      })
      .remainingAccounts(metas)
      .instruction();
    const message = new TransactionMessage({
      payerKey: crank.publicKey,
      recentBlockhash: (await connection.getLatestBlockhash("confirmed")).blockhash,
      instructions: [ComputeBudgetProgram.setComputeUnitLimit({ units: 600_000 }), ix],
    }).compileToV0Message();
    return new VersionedTransaction(message);
  };

  const run = async (c: Case) => {
    const tx = await build(c);
    const sim = await connection.simulateTransaction(tx, {
      // NOT SIGNED AND NOT SENDABLE: the pair of flags that make an unsigned
      // transaction executable in the simulator and nowhere else.
      sigVerify: false,
      replaceRecentBlockhash: true,
      commitment: "confirmed",
      accounts: { encoding: "base64", addresses: [vaultTarget.toBase58(), vaultIn.toBase58(), policyPda.toBase58()] },
    });
    return { sim, size: tx.serialize().length };
  };

  // Learn what the route actually credits, from a simulation that asks nothing
  // of min_out. Every expectation below is then checked against a MEASURED
  // fill rather than against a number we hoped for.
  const probe = await run({ name: "probe", minOut: probeMinOut, expect: "ok", why: "" });
  if (probe.sim.value.err !== null) {
    console.error(`\n✗ the cloned route does not execute at all:`);
    console.error(`  err: ${JSON.stringify(probe.sim.value.err)}`);
    (probe.sim.value.logs ?? []).slice(-25).forEach((l) => console.error(`  ${l}`));
    process.exit(1);
  }
  const post = probe.sim.value.accounts ?? [];
  const targetPost = decodeTokenAccount(vaultTarget, post[0] ?? null);
  const inPost = decodeTokenAccount(vaultIn, post[1] ?? null);
  const usdcBefore = BigInt((await connection.getTokenAccountBalance(vaultIn, "confirmed")).value.amount);
  const credit = targetPost.amount; // destination ATA was created empty in this run
  const withheld = targetPost.withheld;
  const grossDelivered = credit + withheld;
  const spent = usdcBefore - inPost.amount;

  console.log(`\nMEASURED on the cloned route (legacy-equivalent tx ${probe.size} B, ${probe.sim.value.unitsConsumed} CU):`);
  console.log(`  spent        ${spent} USDC raw  (amount_in ${amountIn})`);
  console.log(`  CREDIT       ${credit}   <- what the vault's account gains, and what invest() measures`);
  console.log(`  withheld     ${withheld}   <- Token-2022 fee held inside the destination`);
  console.log(`  gross        ${grossDelivered}  = credit + withheld`);
  console.log(`  quoted       ${quotedOut}`);
  const bps = (a: bigint, b: bigint) => (Number(a - b) / Number(b)) * 10_000;
  console.log(`  credit drift ${bps(credit, quotedOut).toFixed(3)} bps   gross drift ${bps(grossDelivered, quotedOut).toFixed(3)} bps`);

  // WHY THE CREDIT BEATS THE QUOTE HERE, AND WHY THAT CONFIRMS RATHER THAN
  // CONTRADICTS THE MAINNET RESULT. Jupiter quoted this route under mainnet's
  // CURRENT rate; the cloned validator sits at epoch 0 and so applies the
  // mint's OLDER rate. Same gross out of the AMM, less withheld on the way in.
  // If the quote equals the gross netted at the MAINNET rate, to the raw unit,
  // then this venue quotes NET and the basis question is settled here too.
  const mainnetRate: TransferFeeRate = { epoch: 0n, basisPoints: route.mainnetTransferFeeBps, maximumFee: local.maximumFee };
  const netAtMainnetRate = netOfTransferFee(grossDelivered, mainnetRate);
  const netAtLocalRate = netOfTransferFee(grossDelivered, local);
  console.log(`  net(gross, ${String(mainnetRate.basisPoints).padStart(3)} bps mainnet) = ${netAtMainnetRate}  ${netAtMainnetRate === quotedOut ? "== QUOTE exactly -> this venue quotes NET" : "!= quote"}`);
  console.log(`  net(gross, ${String(local.basisPoints).padStart(3)} bps local  ) = ${netAtLocalRate}  ${netAtLocalRate === credit ? "== CREDIT exactly -> the fee is the only difference" : "!= credit"}`);

  // The gross-derived min_out: the number a caller gets by believing the
  // destination is credited the gross. If the venue quoted net, its own
  // threshold is already below the credit and would NOT fail — so the
  // gross-up of the measured credit is used, which is the same mistake
  // expressed against the fill that actually happened.
  const grossMinOut = threshold > credit ? threshold : credit + transferFeeOn(grossDelivered, local);
  const grossSource = threshold > credit ? "the venue's own threshold" : "the gross-up of the measured credit";

  await setPolicy(NET_FLOOR_WAD);

  const cases: readonly Case[] = [
    { name: "guard 1  extra vault account", minOut: safeMinOut, extraAccount: vaultWsol, expect: ERR.DisallowedVaultAccount,
      why: "a third vault-owned token account in the route is one the deltas cannot see" },
    { name: "venue pin  wrong program", minOut: safeMinOut, venueProgramOverride: TOKEN_PROGRAM_ID, expect: ERR.WrongVenue,
      why: "venue_program must equal the owner-signed policy.venue_program" },
    { name: "guard 4  GROSS min_out", minOut: grossMinOut, expect: ERR.FillTooSmall,
      why: `min_out from ${grossSource} is a number about money the vault never receives` },
    { name: "guard 4  NET min_out", minOut: safeMinOut, expect: "ok",
      why: "min_out = threshold - fee(threshold), the largest fill guard that cannot fire on an honest fill" },
    // THE DELTA, PINNED TO A RAW UNIT. The program never reports `received`,
    // so it is bracketed instead: min_out = credit is accepted and credit + 1
    // is refused, which is only possible if the delta invest() measured is
    // EXACTLY the net credit — not the gross, and not an approximation.
    { name: "delta == credit", minOut: credit, expect: "ok",
      why: "the measured delta is at least the NET credit" },
    { name: "delta == credit + 1", minOut: credit + 1n, expect: ERR.FillTooSmall,
      why: "and no more than it — so invest() measured the net, to the raw unit" },
  ];

  console.log(`\nCASES  (gross min_out ${grossMinOut}, safe min_out ${safeMinOut}, measured credit ${credit})`);
  let failures = 0;
  for (const c of cases) {
    const { sim, size } = await run(c);
    const err = sim.value.err;
    const custom = err !== null && typeof err === "object" && "InstructionError" in err
      ? ((err as { InstructionError: [number, { Custom?: number }] }).InstructionError[1] ?? {}).Custom
      : undefined;
    const got = err === null ? "ok" : (custom ?? JSON.stringify(err));
    const pass = got === c.expect;
    if (!pass) failures += 1;
    console.log(`  ${pass ? "PASS" : "FAIL"}  ${c.name.padEnd(30)} min_out ${String(c.minOut).padStart(9)}  expected ${String(c.expect).padEnd(6)} got ${got}  (${size} B)`);
    console.log(`        ${c.why}`);
    if (!pass) (sim.value.logs ?? []).slice(-12).forEach((l) => console.log(`        | ${l}`));
    if (pass && c.expect === "ok") {
      const p = decodeTokenAccount(vaultTarget, (sim.value.accounts ?? [])[0] ?? null);
      // The policy account's post-state, decoded from the program's own write:
      // lifetime_invested is the MEASURED spend, not the claimed amount_in.
      const policyPost = (sim.value.accounts ?? [])[2];
      console.log(`        credit ${p.amount} >= min_out ${c.minOut}  (margin ${p.amount - c.minOut})`);
      if (policyPost !== undefined && policyPost !== null) {
        // The program's OWN record, decoded from the account it just wrote:
        // record()/lifetime_invested take the MEASURED spend, never amount_in.
        const decoded = program.coder.accounts.decode("investmentPolicy", Buffer.from(policyPost.data[0]!, "base64")) as {
          readonly lifetimeInvested: anchor.BN;
        };
        console.log(`        policy.lifetime_invested = ${decoded.lifetimeInvested.toString()} (measured spend; amount_in was ${amountIn})`);
      }
    }
  }

  // The corollary: a leg floor stated in GROSS terms refuses the CORRECT
  // min_out with FloorTooLow, before the CPI ever runs.
  await setPolicy(GROSS_FLOOR_WAD);
  const corollary = await run({ name: "floor", minOut: safeMinOut, expect: ERR.FloorTooLow, why: "" });
  const cErr = corollary.sim.value.err;
  const cCustom = cErr !== null && typeof cErr === "object" && "InstructionError" in cErr
    ? ((cErr as { InstructionError: [number, { Custom?: number }] }).InstructionError[1] ?? {}).Custom
    : undefined;
  const cPass = cCustom === ERR.FloorTooLow;
  if (!cPass) failures += 1;
  console.log(`\n  ${cPass ? "PASS" : "FAIL"}  corollary  leg floor in GROSS terms   min_out_rate_wad ${GROSS_FLOOR_WAD}`);
  console.log(`        expected ${ERR.FloorTooLow} (FloorTooLow) got ${cCustom ?? "ok"} — the safe (net) min_out is BELOW a gross-derived floor,`);
  console.log(`        so invest() refuses the correct number before the CPI. Per-leg floors must be set in net terms.`);
  await setPolicy(NET_FLOOR_WAD);

  console.log(failures === 0 ? `\n✓ ALL ${cases.length + 1} CASES AS EXPECTED` : `\n✗ ${failures} CASE(S) UNEXPECTED`);
  process.exit(failures === 0 ? 0 : 1);
}

main().catch((error) => {
  console.error(`\n✗ ${error instanceof Error ? error.stack ?? error.message : String(error)}`);
  process.exit(1);
});
