#!/usr/bin/env bash
# THE JUPITER GUARD PROOF, one command:
#
#   ./scripts/jupiter-fork.sh
#
# Buys real FIGUREAI (Token-2022, transfer fee) with the vault's USDC through a
# REAL Jupiter sharedAccountsRoute, against mainnet state cloned into a local
# validator, driven by invest() — and proves what jupiter-sim.ts could not:
# that the delta OUR PROGRAM records is the NET credit, and that a min_out
# derived from a gross quote reverts.
#
# No mainnet transaction is ever sent. The only keys involved are two local
# test identities generated by phase 1 and funded by local airdrop.
set -euo pipefail
cd "$(dirname "$0")/.."
RPC="${MAINNET_RPC:-https://api.mainnet-beta.solana.com}"
LOCAL_RPC="http://127.0.0.1:8899"
LOG=/tmp/jupiter-fork-validator.log

command -v solana-test-validator >/dev/null || { echo "solana-test-validator not on PATH" >&2; exit 1; }
[ -f target/deploy/sip_vault.so ] || { echo "target/deploy/sip_vault.so is missing: run anchor build first" >&2; exit 1; }

echo "── phase 1: quote a single-hop route on mainnet and work out what to clone ──"
npx tsx scripts/jupiter-fork-setup.ts

PROGRAM=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("target/idl/sip_vault.json")).address)')
ADMIN=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("scripts/.local/jupiter-route.json")).admin)')
USDC_ACCT=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("scripts/.local/jupiter-vault-usdc.json")).pubkey)')

CLONE_ARGS=()
while IFS= read -r a; do [ -n "$a" ] && CLONE_ARGS+=(--clone "$a"); done < scripts/.local/jupiter-clones.txt
while IFS= read -r p; do [ -n "$p" ] && CLONE_ARGS+=(--clone-upgradeable-program "$p"); done < scripts/.local/jupiter-programs.txt

echo "── phase 2: start validator (cloning $(( ${#CLONE_ARGS[@]} / 2 )) mainnet entries) ──"
pkill -f solana-test-validator 2>/dev/null || true
sleep 2
rm -rf test-ledger
# --upgradeable-program, not `anchor deploy`: it puts sip_vault at its real
# mainnet address WITH a ProgramData account whose upgrade authority is the
# local admin, which is exactly what init_config checks — and it needs no
# program keypair on disk.
solana-test-validator --reset --quiet \
  --url "$RPC" \
  --upgradeable-program "$PROGRAM" target/deploy/sip_vault.so "$ADMIN" \
  "${CLONE_ARGS[@]}" \
  --account "$USDC_ACCT" scripts/.local/jupiter-vault-usdc.json \
  > "$LOG" 2>&1 &
VALIDATOR=$!
trap 'kill $VALIDATOR 2>/dev/null || true' EXIT

for i in $(seq 1 60); do
  if solana cluster-version -u "$LOCAL_RPC" >/dev/null 2>&1; then break; fi
  if ! kill -0 $VALIDATOR 2>/dev/null; then echo "validator died; see $LOG" >&2; tail -30 "$LOG" >&2; exit 1; fi
  sleep 1
done
solana cluster-version -u "$LOCAL_RPC" >/dev/null 2>&1 || { echo "validator never came up; see $LOG" >&2; tail -30 "$LOG" >&2; exit 1; }
echo "   validator up"

echo "── phase 3: the guards, on the cloned route ──"
npx tsx scripts/jupiter-fork-test.ts
