// Review guards for the vault's money-moving cranks: convert's refusals, wrap_sol
// under the protocol pause, and invest's binding of a fill to the leg it names.
// Named z-review- so mocha --sort runs it after every other spec.
//
// ONE DIFFERENCE PER REFUSAL. Every refused call below is a call that converts
// or invests with exactly one thing changed: the pause, the policy switch, the
// pinned venue, the signer, the floor, the amount, the target mint, the leg.
// Each test asserts the exact NuvemError by name and by its errors.rs number,
// shows that no balance moved, and (where the fixture can) lifts that one thing
// and makes the very same call succeed. So a refusal can only be about the thing
// it names, and deleting the check it names turns the refusal into a success.
//
// SHARED STATE. All spec files share one validator and one ProtocolConfig. This
// file names its own keeper and toggles the protocol pause; after() writes both
// back as before() found them, whatever failed in between. Vaults, policies and
// mints are fresh per test. The toy-venue pool is this file's own variant.
//
// NOT HERE: the rolling day buckets (state.rs rolling_total / record). They move
// with Clock::unix_timestamp / 86_400, and the local validator's clock cannot be
// moved 31 days inside a run.

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  AccountMeta,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  Transaction,
  TransactionInstruction,
} from "@solana/web3.js";
import {
  NATIVE_MINT,
  TOKEN_2022_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  createAssociatedTokenAccountIdempotentInstruction,
  createMint,
  createMintToInstruction,
  createSyncNativeInstruction,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import { assert } from "chai";
// @ts-ignore -- target/types is generated by `anchor build`, which `anchor test` runs before mocha.
import type { SipVault } from "../target/types/sip_vault";
// @ts-ignore -- generated alongside sip_vault.
import type { ToyVenue } from "../target/types/toy_venue";
import { configPdaFor, ensureConfig, pollingConfirm, setKeeper } from "./config-fixture";

// No bigint literals: tsconfig targets ES6, where TypeScript refuses them.
const big = (value: number | string): bigint => BigInt(value);
const bn = (value: bigint): anchor.BN => new anchor.BN(value.toString());

const WAD = big("1000000000000000000");
const ONE_SOL = big(LAMPORTS_PER_SOL);
/** The honest pool's price, 0.04 out per unit in: the rate invest.ts trades at. */
const POOL_RATE_WAD = (WAD * big(4)) / big(100);
/** The owner's conversion floor, 0.03 USDC-raw per lamport: below what the pool pays. */
const CONVERT_FLOOR_WAD = (WAD * big(3)) / big(100);
/** Each leg's floor, 95% of the pool's price, as invest.ts signs it. */
const LEG_FLOOR_WAD = (POOL_RATE_WAD * big(95)) / big(100);
/** The constant convert.rs:106 floors max_per_call at before comparing it with amount_in. */
const CONVERT_CAP_FLOOR = big(1_000_000_000);

/** NuvemError as errors.rs numbers it; Anchor counts custom errors from 6000. */
const NUVEM_ERROR = {
  VaultPaused: 6007,
  InvalidPolicy: 6013,
  InvestingDisabled: 6014,
  WrongVenue: 6015,
  AboveMaximum: 6017,
  FloorTooLow: 6019,
  UnauthorizedCrank: 6022,
  ProtocolPaused: 6023,
};
type NuvemErrorName = keyof typeof NUVEM_ERROR;

/** Toy-venue pool variants this file may take. invest.ts owns 0, 1 and 2. */
const POOL_VARIANTS = [0xc3, 0xc4, 0xc5, 0xc6, 0xc7];

describe("z-review: convert, wrap_sol and invest refuse for the one reason they name", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.sipVault as Program<SipVault>;
  const venue = anchor.workspace.toyVenue as Program<ToyVenue>;
  const connection = pollingConfirm(provider.connection);
  const payer = (provider.wallet as anchor.Wallet).payer;
  const authority = provider.wallet.publicKey;
  const configPda = configPdaFor(program.programId);

  /** The keeper this file names in before(); after() names the one it found. */
  const keeper = Keypair.generate();
  /** Funded, and related to no vault and no config role. */
  const stranger = Keypair.generate();
  /** An honest toy-venue pool, chosen in before(). */
  let pool: PublicKey;

  // ── plumbing ──────────────────────────────────────────────────────────────

  const vaultOf = (owner: PublicKey) =>
    PublicKey.findProgramAddressSync([Buffer.from("vault"), owner.toBuffer()], program.programId)[0];
  const policyOf = (vault: PublicKey) =>
    PublicKey.findProgramAddressSync([Buffer.from("invest"), vault.toBuffer()], program.programId)[0];
  const poolOf = (variant: number) =>
    PublicKey.findProgramAddressSync([Buffer.from("pool"), Buffer.from([variant])], venue.programId)[0];
  const ataOf = (mint: PublicKey, owner: PublicKey, tokenProgram: PublicKey) =>
    getAssociatedTokenAddressSync(mint, owner, true, tokenProgram);
  const createAta = (mint: PublicKey, owner: PublicKey, tokenProgram: PublicKey) =>
    createAssociatedTokenAccountIdempotentInstruction(payer.publicKey, ataOf(mint, owner, tokenProgram), owner, mint, tokenProgram);
  const mintInto = (mint: PublicKey, account: PublicKey, amount: bigint, tokenProgram: PublicKey) =>
    createMintToInstruction(mint, account, payer.publicKey, amount, [], tokenProgram);
  const pay = (to: PublicKey, lamports: bigint) =>
    SystemProgram.transfer({ fromPubkey: payer.publicKey, toPubkey: to, lamports });
  const send = (...instructions: TransactionInstruction[]) =>
    provider.sendAndConfirm(new Transaction().add(...instructions));

  const tokenBalance = async (account: PublicKey): Promise<bigint> =>
    big((await connection.getTokenAccountBalance(account)).value.amount);

  /** Token accounts a test watches, by label. */
  type Watched = Record<string, PublicKey>;
  const balancesOf = async (watched: Watched): Promise<Record<string, bigint>> => {
    const balances: Record<string, bigint> = {};
    for (const label of Object.keys(watched)) balances[label] = await tokenBalance(watched[label]);
    return balances;
  };
  const expectUnchanged = async (watched: Watched, before: Record<string, bigint>, why: string) => {
    const now = await balancesOf(watched);
    for (const label of Object.keys(watched)) {
      assert.strictEqual(now[label].toString(), before[label].toString(), `the vault's ${label} moved: ${why}`);
    }
  };

  /** The AnchorError a failed call carries: .rpc() translates it, and a raw send error still holds the logs. */
  const anchorErrorOf = (error: unknown): anchor.AnchorError | null => {
    if (error instanceof anchor.AnchorError) return error;
    const logs = (error as { logs?: unknown } | null)?.logs;
    return Array.isArray(logs) ? anchor.AnchorError.parse(logs as string[]) : null;
  };

  /**
   * Asserts that sip-vault itself refused `call` with exactly `name`, by name
   * and by number, and returns the error so a test can check where it arose.
   */
  const expectRefusal = async (call: Promise<unknown>, name: NuvemErrorName): Promise<anchor.AnchorError> => {
    const outcome = await call.then(
      () => null,
      (error: unknown) => ({ error }),
    );
    if (outcome === null) return assert.fail(`expected ${name}, but the call succeeded`);
    const refusal = anchorErrorOf(outcome.error);
    if (refusal === null) {
      return assert.fail(`expected ${name}, but the call failed without an Anchor error: ${String(outcome.error)}`);
    }
    assert.strictEqual(refusal.error.errorCode.code, name, `refused, but not for the reason under test: ${refusal.error.errorMessage}`);
    assert.strictEqual(refusal.error.errorCode.number, NUVEM_ERROR[name], `${name} keeps its errors.rs number`);
    assert.strictEqual(refusal.program.toBase58(), program.programId.toBase58(), "refused by sip-vault itself, not by a program it called");
    return refusal;
  };

  /**
   * The refusal came from a require! in `file`, which Anchor logs as file:line,
   * and not from an account constraint, which Anchor logs by account name.
   */
  const expectRaisedIn = (refusal: anchor.AnchorError, file: string) => {
    const origin = refusal.error.origin;
    assert.isTrue(
      typeof origin === "object" && origin.file.endsWith(`/${file}`),
      `expected a require! in ${file}, but the origin is ${JSON.stringify(origin)}`,
    );
  };

  const setProtocolPaused = (paused: boolean) =>
    program.methods.setProtocolPaused(paused).accountsPartial({ authority, config: configPda }).rpc();

  /** Runs `body` with the protocol paused, and unpauses however it ends. */
  const whileProtocolPaused = async (body: () => Promise<void>) => {
    await setProtocolPaused(true);
    try {
      await body();
    } finally {
      await setProtocolPaused(false);
    }
  };

  // ── vaults, policies, the venue ───────────────────────────────────────────

  interface Saver {
    readonly owner: Keypair;
    readonly vault: PublicKey;
    readonly policy: PublicKey;
  }

  /** A fresh owner's vault: profit mode at 20%, running, holding only its rent. */
  const newSaver = async (): Promise<Saver> => {
    const owner = Keypair.generate();
    await send(pay(owner.publicKey, big(2) * ONE_SOL));
    await program.methods
      .createVaultV2(0, 2_000, 20, bn(ONE_SOL), bn(big(0)))
      .accounts({ owner: owner.publicKey })
      .signers([owner])
      .rpc();
    const vault = vaultOf(owner.publicKey);
    return { owner, vault, policy: policyOf(vault) };
  };

  const setVaultPaused = (saver: Saver, paused: boolean) =>
    program.methods
      .setPolicyV2(0, 2_000, 20, paused, bn(ONE_SOL), bn(big(0)))
      .accounts({ owner: saver.owner.publicKey })
      .signers([saver.owner])
      .rpc();

  /** set_invest_policy's arguments, one leg at 100% with LEG_FLOOR_WAD. */
  interface PolicyArgs {
    readonly legMint: PublicKey;
    readonly venueProgram: PublicKey;
    readonly inMint: PublicKey;
    readonly minConvertRateWad: bigint;
    readonly minInvestment: bigint;
    readonly maxPerCall: bigint;
    readonly maxRolling: bigint;
    readonly enabled: boolean;
  }

  const setInvestPolicy = (saver: Saver, args: PolicyArgs) =>
    program.methods
      .setInvestPolicy(
        [{ mint: args.legMint, weightBps: 10_000, minOutRateWad: bn(LEG_FLOOR_WAD) }],
        args.venueProgram,
        args.inMint,
        bn(args.minConvertRateWad),
        bn(args.minInvestment),
        bn(args.maxPerCall),
        bn(args.maxRolling),
        args.enabled,
      )
      .accountsPartial({ owner: saver.owner.publicKey, vault: saver.vault, policy: saver.policy })
      .signers([saver.owner])
      .rpc();

  /**
   * An honest pool at POOL_RATE_WAD: this file's first free variant, or one a
   * spec before it already made with exactly these dials.
   */
  const honestPool = async (): Promise<PublicKey> => {
    for (const variant of POOL_VARIANTS) {
      const address = poolOf(variant);
      const existing = await venue.account.pool.fetchNullable(address);
      if (existing === null) {
        await venue.methods
          .initPool(variant, bn(POOL_RATE_WAD), 0, 0)
          .accountsPartial({ payer: payer.publicKey, pool: address })
          .rpc();
        return address;
      }
      if (existing.skimBps === 0 && existing.overpullBps === 0 && existing.rateWad.toString() === POOL_RATE_WAD.toString()) {
        return address;
      }
    }
    throw new Error(`no toy-venue pool variant in [${POOL_VARIANTS.join(", ")}] is free or honest at 0.04`);
  };

  /** What the honest pool delivers for `amountIn`. */
  const fillOf = (amountIn: bigint) => (amountIn * POOL_RATE_WAD) / WAD;

  /** [amount_in, min_out] little-endian: the toy venue's whole ABI. */
  const venueData = (amountIn: bigint, minOut: bigint) => {
    const data = Buffer.alloc(16);
    data.writeBigUInt64LE(amountIn, 0);
    data.writeBigUInt64LE(minOut, 8);
    return data;
  };

  /** The pool's route, slot by slot in programs/toy-venue/src/lib.rs's order. */
  const routeThrough = (
    vault: PublicKey,
    slots: {
      input: PublicKey; venueIn: PublicKey; venueOut: PublicKey; output: PublicKey;
      inMint: PublicKey; outMint: PublicKey; inProgram: PublicKey; outProgram: PublicKey;
    },
  ): AccountMeta[] => [
    { pubkey: pool, isSigner: false, isWritable: false },
    { pubkey: slots.input, isSigner: false, isWritable: true },
    { pubkey: slots.venueIn, isSigner: false, isWritable: true },
    { pubkey: slots.venueOut, isSigner: false, isWritable: true },
    { pubkey: slots.output, isSigner: false, isWritable: true },
    { pubkey: vault, isSigner: false, isWritable: false }, // the program marks it signer
    { pubkey: slots.inMint, isSigner: false, isWritable: false },
    { pubkey: slots.outMint, isSigner: false, isWritable: false },
    { pubkey: slots.inProgram, isSigner: false, isWritable: false },
    { pubkey: slots.outProgram, isSigner: false, isWritable: false },
  ];

  /** The config as before() found it, for after() to write back. */
  let found: { keeper: PublicKey; paused: boolean } | null = null;

  before(async () => {
    await ensureConfig(program, authority);
    const config = await program.account.protocolConfig.fetch(configPda);
    found = { keeper: config.keeper, paused: config.paused };
    await send(pay(keeper.publicKey, big(2) * ONE_SOL), pay(stranger.publicKey, ONE_SOL / big(10)));
    await setKeeper(program, authority, keeper.publicKey);
    // A pause another spec left behind would refuse everything below for a reason no test names.
    if (config.paused) await setProtocolPaused(false);
    pool = await honestPool();
  });

  after(async () => {
    const prior = found;
    if (prior === null) return; // before() failed before it changed anything
    const unrestored: string[] = [];
    try {
      await setProtocolPaused(prior.paused);
    } catch (error) {
      unrestored.push(`the protocol pause (${prior.paused}): ${String(error)}`);
    }
    try {
      await setKeeper(program, authority, prior.keeper);
    } catch (error) {
      unrestored.push(`the keeper (${prior.keeper.toBase58()}): ${String(error)}`);
    }
    if (unrestored.length > 0) throw new Error(`could not restore the shared config: ${unrestored.join("; ")}`);
  });

  // ── convert ───────────────────────────────────────────────────────────────

  interface ConvertRig extends Saver {
    readonly usdc: PublicKey;
    readonly vaultWsol: PublicKey;
    readonly vaultUsdc: PublicKey;
    readonly venueWsol: PublicKey;
    readonly venueUsdc: PublicKey;
    readonly policyArgs: PolicyArgs;
  }

  /**
   * A fresh vault ready to convert: `wsol` lamports of wSOL in its own account,
   * the pool holding `liquidity` of a fresh USDC, and an enabled policy that
   * pins the toy venue and that USDC, with `policy` over the defaults.
   */
  const convertRig = async (wsol: bigint, liquidity: bigint, policy: Partial<PolicyArgs> = {}): Promise<ConvertRig> => {
    const saver = await newSaver();
    const usdc = await createMint(connection, payer, payer.publicKey, null, 6);
    const vaultWsol = ataOf(NATIVE_MINT, saver.vault, TOKEN_PROGRAM_ID);
    const vaultUsdc = ataOf(usdc, saver.vault, TOKEN_PROGRAM_ID);
    const venueWsol = ataOf(NATIVE_MINT, pool, TOKEN_PROGRAM_ID);
    const venueUsdc = ataOf(usdc, pool, TOKEN_PROGRAM_ID);
    await send(
      createAta(NATIVE_MINT, saver.vault, TOKEN_PROGRAM_ID),
      createAta(usdc, saver.vault, TOKEN_PROGRAM_ID),
      createAta(NATIVE_MINT, pool, TOKEN_PROGRAM_ID),
      createAta(usdc, pool, TOKEN_PROGRAM_ID),
    );
    // As wrap_sol would leave it: lamports in the wSOL account, folded into its balance.
    await send(pay(vaultWsol, wsol), createSyncNativeInstruction(vaultWsol), mintInto(usdc, venueUsdc, liquidity, TOKEN_PROGRAM_ID));
    const policyArgs: PolicyArgs = {
      legMint: Keypair.generate().publicKey, // convert never reads the legs
      venueProgram: venue.programId,
      inMint: usdc,
      minConvertRateWad: CONVERT_FLOOR_WAD,
      minInvestment: big(1_000_000),
      maxPerCall: big(100_000_000),
      maxRolling: big(400_000_000),
      enabled: true,
      ...policy,
    };
    await setInvestPolicy(saver, policyArgs);
    return { ...saver, usdc, vaultWsol, vaultUsdc, venueWsol, venueUsdc, policyArgs };
  };

  /** convert, cranked by the keeper through the honest pool unless `by` says otherwise. */
  const convert = (
    rig: ConvertRig,
    amountIn: bigint,
    minOut: bigint,
    by: { crank?: Keypair; venueProgram?: PublicKey } = {},
  ) => {
    const crank = by.crank ?? keeper;
    return program.methods
      .convert(bn(amountIn), bn(minOut), venueData(amountIn, minOut))
      .accountsPartial({
        crank: crank.publicKey,
        config: configPda,
        vault: rig.vault,
        policy: rig.policy,
        vaultWsol: rig.vaultWsol,
        vaultIn: rig.vaultUsdc,
        venueProgram: by.venueProgram ?? venue.programId,
      })
      .remainingAccounts(
        routeThrough(rig.vault, {
          input: rig.vaultWsol, venueIn: rig.venueWsol, venueOut: rig.venueUsdc, output: rig.vaultUsdc,
          inMint: NATIVE_MINT, outMint: rig.usdc, inProgram: TOKEN_PROGRAM_ID, outProgram: TOKEN_PROGRAM_ID,
        }),
      )
      .signers([crank])
      .rpc();
  };

  const convertWatch = (rig: ConvertRig): Watched => ({ wSOL: rig.vaultWsol, USDC: rig.vaultUsdc });

  /** Exactly amount_in of wSOL left the vault, and exactly the pool's fill of USDC arrived. */
  const expectConverted = async (rig: ConvertRig, before: Record<string, bigint>, amountIn: bigint) => {
    const now = await balancesOf(convertWatch(rig));
    assert.strictEqual((before.wSOL - now.wSOL).toString(), amountIn.toString(), "exactly amount_in of wSOL was sold");
    assert.strictEqual((now.USDC - before.USDC).toString(), fillOf(amountIn).toString(), "and the pool's fill landed in the in-asset account");
  };

  describe("convert refuses, each time for the one thing that differs from a conversion that succeeds", () => {
    const AMOUNT_IN = big(10_000_000); // lamports of wSOL, inside every cap
    const WSOL = big(50_000_000);

    it("while the PROTOCOL is paused (convert.rs:86): nothing moves, and the same call converts once it resumes", async () => {
      const rig = await convertRig(WSOL, fillOf(AMOUNT_IN));
      const before = await balancesOf(convertWatch(rig));

      await whileProtocolPaused(async () => {
        await expectRefusal(convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN)), "ProtocolPaused");
        await expectUnchanged(convertWatch(rig), before, "a paused protocol converts nothing");
      });

      await convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN));
      await expectConverted(rig, before, AMOUNT_IN);
    });

    it("while the OWNER has paused the vault: nothing moves, and the same call converts once the owner resumes it", async () => {
      const rig = await convertRig(WSOL, fillOf(AMOUNT_IN));
      const before = await balancesOf(convertWatch(rig));

      await setVaultPaused(rig, true);
      await expectRefusal(convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN)), "VaultPaused");
      await expectUnchanged(convertWatch(rig), before, "a paused vault converts nothing");

      await setVaultPaused(rig, false);
      await convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN));
      await expectConverted(rig, before, AMOUNT_IN);
    });

    it("while the owner's investment policy is disabled, and converts once the owner enables it", async () => {
      const rig = await convertRig(WSOL, fillOf(AMOUNT_IN), { enabled: false });
      const before = await balancesOf(convertWatch(rig));

      await expectRefusal(convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN)), "InvestingDisabled");
      await expectUnchanged(convertWatch(rig), before, "a disabled policy converts nothing");

      await setInvestPolicy(rig, { ...rig.policyArgs, enabled: true });
      await convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN));
      await expectConverted(rig, before, AMOUNT_IN);
    });

    it("through any venue but the one the policy pins, whichever side names the other program", async () => {
      const rig = await convertRig(WSOL, fillOf(AMOUNT_IN));
      const before = await balancesOf(convertWatch(rig));

      // The policy pins the toy venue; the caller brings another program.
      await expectRefusal(convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN), { venueProgram: program.programId }), "WrongVenue");

      // The policy pins another key; the caller brings the toy venue, which WOULD
      // fill this route. Only the pin stands between this call and a conversion.
      await setInvestPolicy(rig, { ...rig.policyArgs, venueProgram: Keypair.generate().publicKey });
      await expectRefusal(convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN)), "WrongVenue");
      await expectUnchanged(convertWatch(rig), before, "an unpinned venue converts nothing");

      await setInvestPolicy(rig, rig.policyArgs);
      await convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN));
      await expectConverted(rig, before, AMOUNT_IN);
    });

    it("cranked by a stranger with every brake released, and the keeper converts the same call", async () => {
      const rig = await convertRig(WSOL, fillOf(AMOUNT_IN));
      const before = await balancesOf(convertWatch(rig));

      await expectRefusal(convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN), { crank: stranger }), "UnauthorizedCrank");
      await expectUnchanged(convertWatch(rig), before, "a stranger converts nothing");

      await convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN), { crank: keeper });
      await expectConverted(rig, before, AMOUNT_IN);
    });

    it("tells a stranger on a paused vault VaultPaused, not UnauthorizedCrank: convert checks the crank after its brakes", async () => {
      // PINS TODAY'S ORDER. The comment at convert.rs:92-94 says the crank check
      // runs "before the pause/policy checks"; the code runs it after the vault
      // pause, the protocol pause, the policy switch and the venue pin, while
      // invest.rs and wrap_sol.rs run it first. Either order refuses the
      // stranger. This records which refusal the stranger reads, so reordering
      // is a decision someone makes rather than a side effect.
      const rig = await convertRig(WSOL, fillOf(AMOUNT_IN));
      const before = await balancesOf(convertWatch(rig));

      await setVaultPaused(rig, true);
      await expectRefusal(convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN), { crank: stranger }), "VaultPaused");
      await expectUnchanged(convertWatch(rig), before, "a stranger on a paused vault converts nothing");
    });

    it("with a zero conversion floor (convert.rs:101), and converts once the owner signs a floor", async () => {
      const rig = await convertRig(WSOL, fillOf(AMOUNT_IN), { minConvertRateWad: big(0) });
      const before = await balancesOf(convertWatch(rig));

      // A positive min_out: against a zero floor, the comparison at convert.rs:113
      // passes, so only the zero-floor check can refuse this call.
      await expectRefusal(convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN)), "FloorTooLow");
      await expectUnchanged(convertWatch(rig), before, "'accept any price' converts nothing");

      await setInvestPolicy(rig, { ...rig.policyArgs, minConvertRateWad: CONVERT_FLOOR_WAD });
      await convert(rig, AMOUNT_IN, fillOf(AMOUNT_IN));
      await expectConverted(rig, before, AMOUNT_IN);
    });

    it("with min_out one below the owner's floor (convert.rs:113), or zero where the floor rounds to zero; converts at the floor exactly", async () => {
      const rig = await convertRig(WSOL, fillOf(AMOUNT_IN));
      const floor = (AMOUNT_IN * CONVERT_FLOOR_WAD) / WAD;
      assert.strictEqual(floor.toString(), "300000", "0.03 USDC-raw per lamport of 10_000_000 lamports");
      assert.isTrue(fillOf(AMOUNT_IN) > floor, "the pool pays above the floor, so the fill guard cannot be what refuses");
      const before = await balancesOf(convertWatch(rig));

      await expectRefusal(convert(rig, AMOUNT_IN, floor - big(1)), "FloorTooLow");
      // One lamport at 0.03 is a floor of 0, and min_out 0 clears `min_out >= floor`.
      // Only `min_out > 0` refuses it; without that, the pool's zero fill would pass.
      await expectRefusal(convert(rig, big(1), big(0)), "FloorTooLow");
      await expectUnchanged(convertWatch(rig), before, "a min_out under the floor converts nothing");

      // The crank's min_out may equal the owner's floor; the pool still fills at its own price.
      await convert(rig, AMOUNT_IN, floor);
      await expectConverted(rig, before, AMOUNT_IN);
    });

    // convert.rs:106 bounds amount_in, which is LAMPORTS of wSOL, by max_per_call,
    // which the owner writes in the IN-ASSET's raw units (USDC: 6 decimals), and
    // floors it at 1_000_000_000. The two scales meet only by that arithmetic: a
    // 100-USDC per-call cap lets 1 SOL convert per call, and a 1_500-USDC cap lets
    // 1.5 SOL. Both sides of the floor are pinned, each at its exact boundary, with
    // enough wSOL and liquidity that amount_in + 1 would convert if the cap let it.

    it("above max(max_per_call, 1e9) with max_per_call below 1e9: 1 SOL + 1 lamport is refused, 1 SOL converts", async () => {
      const maxPerCall = big(100_000_000); // 100 USDC, in the owner's units
      const cap = CONVERT_CAP_FLOOR; // max(100_000_000, 1_000_000_000)
      const rig = await convertRig(cap + big(1), fillOf(cap + big(1)), { maxPerCall });
      assert.isTrue(cap > maxPerCall, "here the 1e9 floor, not the owner's figure, is the cap");
      const before = await balancesOf(convertWatch(rig));

      await expectRefusal(convert(rig, cap + big(1), fillOf(cap + big(1))), "AboveMaximum");
      await expectUnchanged(convertWatch(rig), before, "one lamport over the cap converts nothing");

      await convert(rig, cap, fillOf(cap));
      await expectConverted(rig, before, cap);
    });

    it("above max(max_per_call, 1e9) with max_per_call above 1e9: the owner's figure, read as lamports, is the boundary", async () => {
      const maxPerCall = big(1_500_000_000); // 1_500 USDC in the owner's units, 1.5 SOL to convert
      const rig = await convertRig(maxPerCall + big(1), fillOf(maxPerCall + big(1)), {
        maxPerCall,
        maxRolling: big(3_000_000_000),
      });
      assert.isTrue(maxPerCall > CONVERT_CAP_FLOOR, "here max_per_call, not the floor, is the cap");
      const before = await balancesOf(convertWatch(rig));

      await expectRefusal(convert(rig, maxPerCall + big(1), fillOf(maxPerCall + big(1))), "AboveMaximum");
      await expectUnchanged(convertWatch(rig), before, "one lamport over the cap converts nothing");

      await convert(rig, maxPerCall, fillOf(maxPerCall));
      await expectConverted(rig, before, maxPerCall);
    });
  });

  // ── wrap_sol ──────────────────────────────────────────────────────────────

  describe("wrap_sol", () => {
    it("refuses while the PROTOCOL is paused: the wSOL balance and the vault's SOL hold still, and the same wrap lands once it resumes", async () => {
      const saver = await newSaver();
      const vaultWsol = ataOf(NATIVE_MINT, saver.vault, TOKEN_PROGRAM_ID);
      await send(pay(saver.vault, ONE_SOL), createAta(NATIVE_MINT, saver.vault, TOKEN_PROGRAM_ID));
      // Every other switch wrap_sol reads says yes: the keeper is named, the
      // vault runs, and the owner opted into converting with a real floor.
      await setInvestPolicy(saver, {
        legMint: Keypair.generate().publicKey,
        venueProgram: venue.programId,
        inMint: Keypair.generate().publicKey,
        minConvertRateWad: CONVERT_FLOOR_WAD,
        minInvestment: big(1),
        maxPerCall: big(1),
        maxRolling: big(1),
        enabled: true,
      });
      const amount = ONE_SOL / big(2);
      const wrap = () =>
        program.methods
          .wrapSol(bn(amount))
          .accountsPartial({
            crank: keeper.publicKey,
            config: configPda,
            vault: saver.vault,
            policy: saver.policy,
            vaultWsol,
            tokenProgram: TOKEN_PROGRAM_ID,
            systemProgram: SystemProgram.programId,
          })
          .signers([keeper])
          .rpc();
      const wsolBefore = await tokenBalance(vaultWsol);
      const vaultLamports = await connection.getBalance(saver.vault);
      const keeperLamports = await connection.getBalance(keeper.publicKey);
      assert.strictEqual(wsolBefore.toString(), "0");

      await whileProtocolPaused(async () => {
        await expectRefusal(wrap(), "ProtocolPaused");
        assert.strictEqual((await tokenBalance(vaultWsol)).toString(), wsolBefore.toString(), "not one lamport became wSOL");
        assert.strictEqual(await connection.getBalance(saver.vault), vaultLamports, "the vault's SOL is still SOL, withdrawable in full");
        assert.strictEqual(await connection.getBalance(keeper.publicKey), keeperLamports, "and the keeper fronted nothing");
      });

      await wrap();
      assert.strictEqual((await tokenBalance(vaultWsol)).toString(), amount.toString(), "unpaused, the same wrap lands");
      assert.strictEqual(await connection.getBalance(saver.vault), vaultLamports - LAMPORTS_PER_SOL / 2, "paid for by the vault");
      assert.strictEqual(await connection.getBalance(keeper.publicKey), keeperLamports, "and the keeper is not out of pocket");
    });
  });

  // ── invest ────────────────────────────────────────────────────────────────

  interface InvestRig extends Saver {
    readonly usdc: PublicKey;
    readonly stock: PublicKey;
    /** A second Token-2022 mint that no leg of the policy buys. */
    readonly second: PublicKey;
    readonly vaultUsdc: PublicKey;
    readonly vaultStock: PublicKey;
    readonly vaultSecond: PublicKey;
    readonly venueUsdc: PublicKey;
    readonly venueStock: PublicKey;
    readonly venueSecond: PublicKey;
  }

  /**
   * A fresh vault with 1_000 USDC staged, an account of its one leg's stock, a
   * FUNDED account of a second Token-2022 mint, and the pool holding both.
   */
  const investRig = async (): Promise<InvestRig> => {
    const saver = await newSaver();
    const usdc = await createMint(connection, payer, payer.publicKey, null, 6);
    const stock = await createMint(connection, payer, payer.publicKey, null, 8, Keypair.generate(), undefined, TOKEN_2022_PROGRAM_ID);
    const second = await createMint(connection, payer, payer.publicKey, null, 8, Keypair.generate(), undefined, TOKEN_2022_PROGRAM_ID);
    const rig: InvestRig = {
      ...saver,
      usdc,
      stock,
      second,
      vaultUsdc: ataOf(usdc, saver.vault, TOKEN_PROGRAM_ID),
      vaultStock: ataOf(stock, saver.vault, TOKEN_2022_PROGRAM_ID),
      vaultSecond: ataOf(second, saver.vault, TOKEN_2022_PROGRAM_ID),
      venueUsdc: ataOf(usdc, pool, TOKEN_PROGRAM_ID),
      venueStock: ataOf(stock, pool, TOKEN_2022_PROGRAM_ID),
      venueSecond: ataOf(second, pool, TOKEN_2022_PROGRAM_ID),
    };
    await send(
      createAta(usdc, saver.vault, TOKEN_PROGRAM_ID),
      createAta(stock, saver.vault, TOKEN_2022_PROGRAM_ID),
      createAta(second, saver.vault, TOKEN_2022_PROGRAM_ID),
    );
    await send(
      createAta(usdc, pool, TOKEN_PROGRAM_ID),
      createAta(stock, pool, TOKEN_2022_PROGRAM_ID),
      createAta(second, pool, TOKEN_2022_PROGRAM_ID),
    );
    await send(
      mintInto(usdc, rig.vaultUsdc, big(1_000_000_000), TOKEN_PROGRAM_ID),
      mintInto(second, rig.vaultSecond, big(500_000_000), TOKEN_2022_PROGRAM_ID),
      mintInto(stock, rig.venueStock, big(10_000_000_000), TOKEN_2022_PROGRAM_ID),
      mintInto(second, rig.venueSecond, big(10_000_000_000), TOKEN_2022_PROGRAM_ID),
    );
    await setInvestPolicy(saver, {
      legMint: stock,
      venueProgram: venue.programId,
      inMint: usdc,
      minConvertRateWad: CONVERT_FLOOR_WAD,
      minInvestment: big(1_000_000),
      maxPerCall: big(100_000_000),
      maxRolling: big(400_000_000),
      enabled: true,
    });
    return rig;
  };

  /** Where a call's fill lands: the vault's account, its mint, and the pool's liquidity of that mint. */
  interface Target {
    readonly account: PublicKey;
    readonly mint: PublicKey;
    readonly venueOut: PublicKey;
  }
  const stockTarget = (rig: InvestRig): Target => ({ account: rig.vaultStock, mint: rig.stock, venueOut: rig.venueStock });
  const secondTarget = (rig: InvestRig): Target => ({ account: rig.vaultSecond, mint: rig.second, venueOut: rig.venueSecond });

  /** invest, cranked by the keeper: USDC through the honest pool into `target`. */
  const invest = (rig: InvestRig, legIndex: number, amountIn: bigint, minOut: bigint, target: Target) =>
    program.methods
      .invest(legIndex, bn(amountIn), bn(minOut), venueData(amountIn, minOut))
      .accountsPartial({
        crank: keeper.publicKey,
        config: configPda,
        vault: rig.vault,
        policy: rig.policy,
        vaultIn: rig.vaultUsdc,
        vaultTarget: target.account,
        targetMint: target.mint,
        venueProgram: venue.programId,
      })
      .remainingAccounts(
        routeThrough(rig.vault, {
          input: rig.vaultUsdc, venueIn: rig.venueUsdc, venueOut: target.venueOut, output: target.account,
          inMint: rig.usdc, outMint: target.mint, inProgram: TOKEN_PROGRAM_ID, outProgram: TOKEN_2022_PROGRAM_ID,
        }),
      )
      .signers([keeper])
      .rpc();

  const investWatch = (rig: InvestRig): Watched => ({
    USDC: rig.vaultUsdc,
    stock: rig.vaultStock,
    "second mint": rig.vaultSecond,
  });

  describe("invest fills only into the mint of the leg it names", () => {
    const AMOUNT_IN = big(10_000_000); // 10 USDC, inside every cap

    it("refuses a funded vault-owned Token-2022 account of a SECOND mint as vault_target/target_mint (invest.rs:128), and nothing moves", async () => {
      const rig = await investRig();
      const minOut = fillOf(AMOUNT_IN);
      assert.isTrue(minOut >= (AMOUNT_IN * LEG_FLOOR_WAD) / WAD, "min_out clears leg 0's floor, so the floor cannot be what refuses");
      const before = await balancesOf(investWatch(rig));
      assert.strictEqual(before["second mint"].toString(), "500000000", "the second mint's account is funded");

      // Everything the account constraints can see is consistent: the vault owns
      // vault_target, and vault_target's mint IS target_mint, because the caller
      // chose both. The route pairs USDC with the second mint through the honest
      // pool, and its fill clears leg 0's floor. Only the handler knows leg 0 buys stock.
      const refusal = await expectRefusal(invest(rig, 0, AMOUNT_IN, minOut, secondTarget(rig)), "InvalidPolicy");
      // vault_target's own constraints raise InvalidPolicy too, logged by account
      // name; this one must be the handler's require!.
      expectRaisedIn(refusal, "invest.rs");
      await expectUnchanged(investWatch(rig), before, "a fill into a mint outside the basket moves nothing");

      // The same call into the leg's own mint invests, so the refusal was the mint.
      await invest(rig, 0, AMOUNT_IN, minOut, stockTarget(rig));
      const after = await balancesOf(investWatch(rig));
      assert.strictEqual((before.USDC - after.USDC).toString(), AMOUNT_IN.toString(), "amount_in was spent");
      assert.strictEqual((after.stock - before.stock).toString(), minOut.toString(), "and the leg's own mint arrived");
      assert.strictEqual(after["second mint"].toString(), before["second mint"].toString(), "and the second mint never moved");
    });

    it("refuses leg_index 1 on a one-leg policy, and nothing moves", async () => {
      const rig = await investRig();
      const minOut = fillOf(AMOUNT_IN);
      const before = await balancesOf(investWatch(rig));

      const refusal = await expectRefusal(invest(rig, 1, AMOUNT_IN, minOut, stockTarget(rig)), "InvalidPolicy");
      // `legs.get(1).ok_or(InvalidPolicy)?` logs neither a file:line (the leg-mint
      // require!) nor an account name (vault_target's constraints).
      assert.isUndefined(refusal.error.origin, `expected the missing leg, but the origin is ${JSON.stringify(refusal.error.origin)}`);
      await expectUnchanged(investWatch(rig), before, "a leg that does not exist buys nothing");

      await invest(rig, 0, AMOUNT_IN, minOut, stockTarget(rig));
      assert.strictEqual(
        ((await tokenBalance(rig.vaultStock)) - before.stock).toString(),
        minOut.toString(),
        "leg 0, the same call otherwise, invests",
      );
    });
  });
});
