// The pasted key, judged before anything is done with it. Every key here is
// generated by @solana/web3.js on the spot — an implementation independent of
// the one under test — and none is ever written down: no real key belongs in a
// test file.

import { base58Encode } from "@sip/solana-core/client";
import { Keypair } from "@solana/web3.js";
import { describe, expect, it } from "vitest";

import { KEY_COPY, isForeignSecret, judgePastedKey, privateKeyForImport, scrubKeyFrom, type DeriveAddress } from "@/lib/import-key";

const fresh = () => {
  const pair = Keypair.generate();
  return { address: pair.publicKey.toBase58(), secret: pair.secretKey, base58: base58Encode(pair.secretKey) };
};

const TWELVE_WORDS = "abandon ability able about above absent absorb abstract absurd abuse access accident";

describe("judgePastedKey: a whole key", () => {
  it("reads base58 of the 64 bytes, and names the wallet the private half opens", async () => {
    const key = fresh();
    expect(await judgePastedKey(key.base58)).toEqual({ kind: "key", address: key.address, format: "base58" });
  });

  it("reads a key file's list of 64 numbers, spaces and line breaks included", async () => {
    const key = fresh();
    const file = `[\n  ${[...key.secret].join(",\n  ")}\n]`;
    expect(await judgePastedKey(file)).toEqual({ kind: "key", address: key.address, format: "json" });
  });

  it("takes surrounding space and one pair of quotes off: a value copied out of a JSON file", async () => {
    const key = fresh();
    expect(await judgePastedKey(`  "${key.base58}"\n`)).toEqual({ kind: "key", address: key.address, format: "base58" });
    expect(await judgePastedKey(`'${key.base58}'`)).toMatchObject({ kind: "key", address: key.address });
  });

  it("says nothing about an empty field", async () => {
    expect(await judgePastedKey("")).toEqual({ kind: "empty" });
    expect(await judgePastedKey("  \n ")).toEqual({ kind: "empty" });
  });
});

describe("judgePastedKey: the likely mistakes, each in its own words", () => {
  it("a recovery phrase, of 12 or 24 words", async () => {
    expect(await judgePastedKey(TWELVE_WORDS)).toEqual({ kind: "refused", reason: "recovery_phrase", message: KEY_COPY.recoveryPhrase });
    expect(await judgePastedKey(`${TWELVE_WORDS}\n${TWELVE_WORDS}`)).toMatchObject({ reason: "recovery_phrase" });
  });

  it("an EVM key, with or without 0x", async () => {
    const hex = "4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318";
    expect(await judgePastedKey(`0x${hex}`)).toMatchObject({ reason: "evm_key", message: KEY_COPY.evmKey });
    expect(await judgePastedKey(hex)).toMatchObject({ reason: "evm_key" });
  });

  it("64 characters valid in both alphabets are an EVM key, not base58", async () => {
    // No 0, O, I or l: every character is base58 as well as hex.
    const both = "4c1883a69112937d6231471b5dbb6234fe5129617182792ae468d11a3f362318";
    expect(both).toMatch(/^[1-9a-f]{64}$/);
    expect(await judgePastedKey(both)).toMatchObject({ reason: "evm_key" });
  });

  it("a wallet address, or the 32-byte seed alone, in base58 or as a list", async () => {
    const key = fresh();
    expect(await judgePastedKey(key.address)).toEqual({ kind: "refused", reason: "half_key", message: KEY_COPY.halfKey });
    expect(await judgePastedKey(JSON.stringify([...key.secret.slice(0, 32)]))).toMatchObject({ reason: "half_key" });
  });

  it("a key file of the wrong size, or with a number that is not a byte", async () => {
    const key = fresh();
    expect(await judgePastedKey(JSON.stringify([...key.secret.slice(0, 63)]))).toEqual({ kind: "refused", reason: "key_file", message: KEY_COPY.keyFile(63) });
    const notAByte = [...key.secret];
    notAByte[5] = 256;
    expect(await judgePastedKey(JSON.stringify(notAByte))).toMatchObject({ reason: "key_file" });
    expect(await judgePastedKey("[1, 2,")).toMatchObject({ reason: "not_a_key" });
  });

  it("anything else: a typo outside base58, the key in hex, a sentence", async () => {
    const key = fresh();
    expect(await judgePastedKey(`${key.base58.slice(0, 40)}0${key.base58.slice(41)}`)).toMatchObject({ reason: "not_a_key", message: KEY_COPY.notAKey });
    expect(await judgePastedKey(Buffer.from(key.secret).toString("hex"))).toMatchObject({ reason: "not_a_key" });
    expect(await judgePastedKey("my key is in phantom")).toMatchObject({ reason: "not_a_key" });
    expect(await judgePastedKey('{"secretKey":1}')).toMatchObject({ reason: "not_a_key" });
  });
});

describe("judgePastedKey: the address comes from the private half", () => {
  it("refuses a key whose public half is another wallet's", async () => {
    const key = fresh();
    const other = fresh();
    const spliced = new Uint8Array([...key.secret.slice(0, 32), ...other.secret.slice(32)]);
    expect(await judgePastedKey(base58Encode(spliced))).toEqual({ kind: "refused", reason: "damaged", message: KEY_COPY.damaged });
  });

  it("refuses one changed bit in either half", async () => {
    const key = fresh();
    for (const index of [3, 40]) {
      const bent = new Uint8Array(key.secret);
      bent[index] = (bent[index] ?? 0) ^ 1;
      expect(await judgePastedKey(JSON.stringify([...bent]))).toMatchObject({ reason: "damaged" });
    }
  });

  it("refuses rather than guesses when the browser cannot derive a key", async () => {
    const key = fresh();
    const noEd25519: DeriveAddress = async () => null;
    expect(await judgePastedKey(key.base58, noEd25519)).toEqual({ kind: "refused", reason: "unchecked", message: KEY_COPY.unchecked });
  });

  it("hands the derivation the seed alone, and zeroes it once the verdict is in", async () => {
    const key = fresh();
    let seen: Uint8Array | null = null;
    let atCall = "";
    const spy: DeriveAddress = async (seed) => {
      seen = seed;
      atCall = base58Encode(seed);
      return key.address;
    };
    expect(await judgePastedKey(key.base58, spy)).toMatchObject({ kind: "key" });
    expect(atCall).toBe(base58Encode(key.secret.slice(0, 32)));
    expect(seen).not.toBeNull();
    expect([...(seen as unknown as Uint8Array)].every((byte) => byte === 0)).toBe(true);
  });
});

describe("privateKeyForImport", () => {
  it("is base58 of the 64 bytes, whichever way the key was pasted", () => {
    const key = fresh();
    expect(privateKeyForImport(key.base58)).toBe(key.base58);
    expect(privateKeyForImport(` "${key.base58}" `)).toBe(key.base58);
    expect(privateKeyForImport(JSON.stringify([...key.secret]))).toBe(key.base58);
  });

  it("is null for anything that is not a whole key", () => {
    const key = fresh();
    for (const text of ["", TWELVE_WORDS, key.address, `0x${"ab".repeat(32)}`, JSON.stringify([...key.secret.slice(0, 32)])]) {
      expect(privateKeyForImport(text)).toBeNull();
    }
  });
});

describe("isForeignSecret: what the field drops the moment it is recognised", () => {
  it("a recovery phrase, and a whole EVM key, quoted or not", async () => {
    const hex = "4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318";
    for (const text of [TWELVE_WORDS, `0x${hex}`, hex, `"0x${hex}"`, ` '${hex}'\n`]) {
      expect(isForeignSecret(text, await judgePastedKey(text)), text).toBe(true);
    }
  });

  it("nothing a Solana key could be on its way to, nor a key itself", async () => {
    const key = fresh();
    for (const text of ["0x4c08", key.base58.slice(0, 30), key.address, key.base58, "my key is"]) {
      expect(isForeignSecret(text, await judgePastedKey(text)), text).toBe(false);
    }
  });
});

describe("scrubKeyFrom: an error raised while the key was handed over keeps no run of 8 or more of its characters", () => {
  it("takes out the whole key, a clipped piece of 8 characters or more, and leaves shorter runs and other text", () => {
    const key = fresh();
    expect(scrubKeyFrom(`bad key ${key.base58} here`, key.base58)).toBe("bad key [redacted] here");
    const piece = key.base58.slice(10, 30);
    expect(scrubKeyFrom(`input …${piece}… rejected`, key.base58)).toBe("input …[redacted]… rejected");
    expect(scrubKeyFrom(`ok ${key.base58.slice(0, 7)} ok`, key.base58)).toBe(`ok ${key.base58.slice(0, 7)} ok`);
    expect(scrubKeyFrom("Failed to import wallet", key.base58)).toBe("Failed to import wallet");
  });
});

describe("the key-file messages", () => {
  it("count in words that agree, and name a value that is not a byte for what it is", async () => {
    expect(KEY_COPY.keyFile(1)).toBe("That list has 1 number. A Solana key file holds 64, each from 0 to 255.");
    expect(await judgePastedKey("[7]")).toMatchObject({ reason: "key_file", message: KEY_COPY.keyFile(1) });
    const key = fresh();
    const bent = [...key.secret];
    bent[0] = 300;
    expect(await judgePastedKey(JSON.stringify(bent))).toEqual({ kind: "refused", reason: "key_file", message: KEY_COPY.keyFileByte });
  });
});
