// Environment loading. Refuses to start rather than guessing.
//
// Ported from the keeper of the project this was forked from (src/config.ts (the byte-exact sentinel, the)
// key-shaped env sweep, `shape()`, the address and number readers, and the rule
// that a refusal never echoes a value); reshaped for the worker's frozen
// WorkerConfig and for DESIGN.md §0.1, which is stricter than the old keeper
// in one way: outside live mode the secrets are not merely withheld, they are
// never READ.
//
// The governing rule of this file is that "unverified" is never permission to
// proceed. Every value that could silently produce a wrong pull — the chain id,
// the executor, the broadcast gate — is either present and well-formed, or the
// process exits before it can do any work. Nothing here has a fallback that
// "probably works".
//
// TWO THINGS ARE DELIBERATELY ASYMMETRIC:
//
//   * DRY RUN NEEDS NO SECRET. In dry-run mode SIP_ATTESTER_PRIVATE_KEY and the
//     Privy secrets are never read from the environment at all: the variables
//     are deleted by NAME, without their values ever crossing into this
//     process's heap. That is not an optimisation, it is the enforcement of
//     non-negotiable #1: a dry run cannot pull because the process does not
//     hold anything that could sign one.
//
//   * LIVE MODE NEEDS AN EXACT SENTENCE. SIP_WORKER_ALLOW_BROADCAST must equal
//     a specific literal string, compared byte for byte. A truthiness check
//     would be enabled by `=0`, `=false` and `=no`, all of which a human writes
//     when they mean the opposite; a trimmed comparison would be enabled by a
//     value that was pasted with a newline.
//
// AND ONE RULE ABOUT WHAT A REFUSAL MAY SAY.
//
// No message built in this file ever contains an environment VALUE. Config
// validation runs before the logger exists, and bin/worker.mts writes each
// problem straight to stderr, so a message that echoes what it read publishes it
// to container logs — which are shipped, rotated and pasted into bug reports. So
// a refusal names the VARIABLE, the shape it expected, and the SHAPE it got —
// length and character class, never content: see `shape()`. Three further
// layers back that up:
//
//   1. Any 0x+64-hex value found anywhere in the environment is registered with
//      the Redactor before validation begins, whatever variable it arrived in.
//      A key pasted into the wrong name is redacted from every log line even
//      though this file has no idea it is a key.
//   2. Every problem and warning string is scrubbed through that Redactor on the
//      way out, so a future author who interpolates a value still cannot leak it.
//   3. The secret-bearing variables are removed from the environment in EVERY
//      mode, so a child process or a crash handler that dumps `process.env`
//      cannot see them.

import { isAddress } from "viem";
import { CHAIN_ID } from "./chain/constants.js";
import { Redactor, sharedRedactor } from "./log.js";
import type { Address, Hex, WorkerConfig, WorkerMode } from "./types.js";

/** The literal acknowledgement that arms the worker. Nothing else does. */
export const BROADCAST_ACK = "i-understand-this-moves-real-funds";

/**
 * NO DEPLOYMENT IS BUILT IN, and that is the point.
 *
 * This constant used to carry Nuvem's 2026-08-16 topology as a FALLBACK, so a
 * worker with an empty SIP_VAULT_FACTORY silently aimed at it. That deployment's
 * trading accounts hold a savings rate meaning a PERCENTAGE OF PROFIT — 1000 to
 * 3000 bps, read from chain on 2026-09-08 — and Phase 0 applies that rate to the
 * attested cash field, which here is a volume. Arming such a worker would have
 * skimmed twenty percent of notional instead of the twenty basis points the user
 * agreed to: a hundred times too much, on somebody else's wallet.
 *
 * So the factory and the executor are REQUIRED. A missing one is a startup
 * problem with a sentence explaining it, never a default that happens to point
 * somewhere real.
 */

/** Tuning defaults from DESIGN.md §2 (config). */
export const DEFAULTS = {
  pollMs: 300_000,
  finalityMarginL2: 64n,
  maxLogSpan: 10_000n,
} as const;

/**
 * Read only in live mode; deleted from the environment in every mode. Both
 * spellings of the Privy authorization key, because the key is generated by a
 * script that has to name it somewhere and a near-miss is invisible until live
 * mode: the value is present, correct and simply not looked at.
 */
export const SECRET_VARS = [
  "SIP_ATTESTER_PRIVATE_KEY",
  "PRIVY_APP_SECRET",
  "PRIVY_AUTHORIZATION_PRIVATE_KEY",
  "PRIVY_AUTHORIZATION_KEY",
] as const;

export type ConfigResult =
  | {
      readonly ok: true;
      readonly config: WorkerConfig;
      readonly warnings: readonly string[];
      readonly redactor: Redactor;
    }
  | {
      readonly ok: false;
      /** Already scrubbed; a caller may write these straight to stderr. */
      readonly problems: readonly string[];
      readonly redactor: Redactor;
    };

/** What `loadConfig` throws. `problems` are scrubbed; so is `message`. */
export class ConfigError extends Error {
  override readonly name = "ConfigError";

  constructor(readonly problems: readonly string[]) {
    super(`Refusing to start:\n${problems.map((problem) => `  - ${problem}`).join("\n")}`);
  }
}

export interface LoadConfigOptions {
  /** Where warnings go. Defaults to stderr, because there is no logger yet. */
  readonly onWarning?: (message: string) => void;
  /** Defaults to `sharedRedactor`, which is what the default logger uses. */
  readonly redactor?: Redactor;
}

const first = (env: NodeJS.ProcessEnv, names: readonly string[]): string | undefined => {
  for (const name of names) {
    const value = env[name];
    if (value !== undefined && value.trim() !== "") return value.trim();
  }
  return undefined;
};

const PRIVATE_KEY = /^0x[0-9a-fA-F]{64}$/;
const HEX = /^0x[0-9a-fA-F]*$/;
const ADDRESS_SHAPE = /^0x[0-9a-fA-F]{40}$/;
const ZERO_ADDRESS: Address = "0x0000000000000000000000000000000000000000";

/**
 * Describes a rejected environment value WITHOUT reproducing any of it.
 *
 * Length and character class are enough to diagnose every mistake that actually
 * happens — a truncated address, a decimal where hex was wanted, a stray quote,
 * a pasted private key — and none of them is enough to use. Deliberately not
 * even a prefix: the first four bytes of a signing key are four bytes of a
 * signing key, and there is no diagnostic that needs them.
 *
 * The key-shaped case gets its own sentence because it is the one mistake with a
 * catastrophic version: a variable holding what is unmistakably a private key is
 * worth saying out loud so the operator rotates it instead of just fixing the
 * typo.
 */
export function shape(value: string): string {
  if (value.length === 0) return "an empty value";
  if (PRIVATE_KEY.test(value)) {
    return (
      `a ${value.length}-character value shaped exactly like a 0x-prefixed 32-byte private key ` +
      "(the value itself is withheld — if a signing key was pasted into this variable, treat it " +
      "as exposed and rotate it)"
    );
  }
  const kind = /^\s+$/.test(value)
    ? "whitespace-only"
    : HEX.test(value)
      ? "0x-prefixed hex"
      : /^[+-]?[0-9]+$/.test(value)
        ? "decimal-integer"
        : /^[+-]?[0-9]*\.[0-9]+$/.test(value)
          ? "decimal-fraction"
          : "neither-hex-nor-numeric";
  return `a ${value.length}-character ${kind} value`;
}

/**
 * Reads a secret from the first of `names` that is set, registers it with the
 * Redactor, and removes EVERY spelling from the environment — the one that won
 * and the ones that lost. Live mode only; the dry-run path deletes by name
 * without calling this.
 */
function takeSecret(env: NodeJS.ProcessEnv, names: readonly string[], label: string, redactor: Redactor): string | undefined {
  const value = first(env, names);
  for (const name of names) delete env[name];
  if (value !== undefined) redactor.register(value, label);
  return value;
}

/**
 * An address that has no default. Absent is a problem, not a fallback: the two
 * addresses this applies to decide whose vault the money lands in.
 */
function requiredAddress(value: string | undefined, name: string, problems: string[]): Address {
  const candidate = (value ?? "").trim();
  if (candidate === "") {
    problems.push(
      `${name} is not set. SIP does not ship a default deployment: Nuvem's vaults hold accounts whose ` +
        `savings rate means a percentage of PROFIT, and this worker attests VOLUME, so aiming at one would ` +
        `skim about a hundred times what the user agreed to. Deploy SIP's own factory and set this.`,
    );
    return ZERO_ADDRESS_FALLBACK;
  }
  return address(candidate, ZERO_ADDRESS_FALLBACK, name, problems);
}

/** The first block worth scanning for this deployment's factory. No default, same reasoning. */
function requiredBlock(value: string | undefined, name: string, problems: string[]): bigint {
  const candidate = (value ?? "").trim();
  if (candidate === "") {
    problems.push(`${name} is not set — the block the SIP factory was deployed at, so the log scan has a floor.`);
    return 0n;
  }
  return nonNegativeBigInt(candidate, 0n, name, problems);
}

/** Only ever reached when a problem was already recorded; loadConfig throws before it is used. */
const ZERO_ADDRESS_FALLBACK = "0x0000000000000000000000000000000000000000" as Address;

function address(value: string | undefined, fallback: Address, name: string, problems: string[]): Address {
  const candidate = value ?? fallback;
  if (!ADDRESS_SHAPE.test(candidate)) {
    problems.push(
      `${name} is not a valid address — expected 0x followed by 40 hex characters (42 in total), ` +
        `got ${shape(candidate)}.`,
    );
    return ZERO_ADDRESS;
  }
  // Strict: a mixed-case address must carry a correct EIP-55 checksum. A typo in
  // a checksummed address is a different contract; lowercase is accepted as is.
  if (!isAddress(candidate)) {
    problems.push(`${name} is a mixed-case address whose EIP-55 checksum does not match: retype it, or set it all-lowercase.`);
    return ZERO_ADDRESS;
  }
  return candidate.toLowerCase() as Address;
}

function nonNegativeBigInt(value: string | undefined, fallback: bigint, name: string, problems: string[]): bigint {
  if (value === undefined) return fallback;
  let parsed: bigint;
  try {
    parsed = BigInt(value);
  } catch {
    problems.push(`${name} must be an integer, got ${shape(value)}.`);
    return fallback;
  }
  if (parsed < 0n) {
    problems.push(`${name} must not be negative, got ${shape(value)}.`);
    return fallback;
  }
  return parsed;
}

function positiveInteger(value: string | undefined, fallback: number, name: string, problems: string[]): number {
  if (value === undefined) return fallback;
  const parsed = /^[+-]?[0-9]+$/.test(value) ? Number(value) : Number.NaN;
  if (!Number.isSafeInteger(parsed) || parsed <= 0) {
    problems.push(`${name} must be a positive integer, got ${shape(value)}.`);
    return fallback;
  }
  return parsed;
}

const hostOf = (url: string): string => {
  try {
    return new URL(url).host;
  } catch {
    return "<invalid>";
  }
};

/** Fields of the config that are safe to put in a log line or a heartbeat. */
export function describeConfig(config: WorkerConfig): Record<string, unknown> {
  return {
    mode: config.mode,
    chainId: config.chainId,
    // Hosts only: the URLs carry API keys and passwords.
    rpcHosts: config.rpcUrls.map(hostOf),
    factory: config.factory,
    executor: config.executor,
    logsFromBlock: config.logsFromBlock.toString(),
    ledger: config.databaseUrl === null ? "memory" : `postgres@${hostOf(config.databaseUrl)}`,
    pollMs: config.pollMs,
    finalityMarginL2: config.finalityMarginL2.toString(),
    maxLogSpan: config.maxLogSpan.toString(),
    attesterKeyPresent: config.attesterPrivateKey !== null,
    privyAppId: config.privy === null ? null : config.privy.appId,
  };
}

/**
 * Mechanism 1 for a plain object. The frozen WorkerConfig cannot carry
 * `Secret`s, so the object itself learns to describe rather than dump itself:
 * `JSON.stringify(config)` and `util.inspect(config)` (hence `console.log`)
 * yield `describe()`. Both hooks are non-enumerable, so spread and
 * `Object.entries` still see the real fields — a teammate's `{...config}` keeps
 * working, and only the two serializers are diverted.
 */
function guarded<T extends object>(value: T, describe: () => Record<string, unknown>): T {
  Object.defineProperty(value, "toJSON", { value: describe, enumerable: false, writable: false, configurable: false });
  Object.defineProperty(value, Symbol.for("nodejs.util.inspect.custom"), {
    value: describe,
    enumerable: false,
    writable: false,
    configurable: false,
  });
  return value;
}

/**
 * Pure, side-effect-free reading of the environment into a result — EXCEPT for
 * the two side effects that are the point: the secret-bearing variables are
 * deleted from `env`, and every secret read is registered with `redactor`.
 * Never throws. `loadConfig` is the throwing wrapper the binary uses.
 */
export function parseConfig(env: NodeJS.ProcessEnv, redactor: Redactor = sharedRedactor): ConfigResult {
  const problems: string[] = [];
  const warnings: string[] = [];

  // --- the broadcast gate, evaluated first so its outcome shapes everything ---
  //
  // Read RAW, not trimmed. Every other setting is trimmed for convenience, but
  // the arming sentinel is compared byte for byte: the failure mode of strictness
  // is a confusing refusal, which is safe, while the failure mode of leniency is
  // a broadcast nobody intended. The warning names whitespace explicitly so the
  // refusal is not actually confusing.
  const ack = env.SIP_WORKER_ALLOW_BROADCAST;
  const mode: WorkerMode = ack === BROADCAST_ACK ? "live" : "dry-run";
  if (mode === "dry-run" && ack !== undefined && ack !== "") {
    warnings.push(
      "SIP_WORKER_ALLOW_BROADCAST is set but is not the exact string " +
        `${JSON.stringify(BROADCAST_ACK)} — compared byte for byte, so surrounding whitespace, ` +
        "a trailing newline or a change of case does not count. Staying in dry run; no secret was read.",
    );
  }

  // --- secrets: read ONLY in live mode, removed from the environment always ---
  let attesterPrivateKey: Hex | null = null;
  let privy: WorkerConfig["privy"] = null;
  if (mode === "live") {
    const attesterRaw = takeSecret(env, ["SIP_ATTESTER_PRIVATE_KEY"], "attesterKey", redactor);
    if (attesterRaw === undefined) {
      problems.push("Live mode requires SIP_ATTESTER_PRIVATE_KEY: the key registered in AttesterRegistry. It signs volume and holds no funds.");
    } else if (!PRIVATE_KEY.test(attesterRaw)) {
      problems.push(
        `SIP_ATTESTER_PRIVATE_KEY is not a 0x-prefixed 32-byte hex private key (66 characters): it holds ${shape(attesterRaw)}.`,
      );
    } else {
      attesterPrivateKey = attesterRaw as Hex;
    }

    // The pull is signed by Privy through the app's authorization key; the
    // worker never holds a trading key (DESIGN.md §0.2). All three are required:
    // a seat without its key cannot sign, and a key without its app cannot be
    // presented.
    const appId = first(env, ["PRIVY_APP_ID"]);
    // An id, not a secret: read with `first` so it stays legible in logs and in
    // the startup line. It is required all the same -- the seat throws without
    // it, and it threw AT STARTUP, after arming, which is the worst possible
    // moment to discover a missing variable.
    const signerId = first(env, ["PRIVY_SIGNER_ID"]);
    const appSecret = takeSecret(env, ["PRIVY_APP_SECRET"], "privyAppSecret", redactor);
    const authorizationPrivateKey = takeSecret(
      env,
      ["PRIVY_AUTHORIZATION_PRIVATE_KEY", "PRIVY_AUTHORIZATION_KEY"],
      "privyAuthorizationKey",
      redactor,
    );
    if (appId === undefined) problems.push("Live mode requires PRIVY_APP_ID.");
    if (signerId === undefined || signerId === "") {
      problems.push(
        "Live mode requires PRIVY_SIGNER_ID: the key quorum id the website seats wallets with. " +
          "A wallet counts as ours only when that id is among its additional signers; without it every " +
          "additional signer would answer for ours and the pull would be planned against a seat we do not hold.",
      );
    }
    if (appSecret === undefined) problems.push("Live mode requires PRIVY_APP_SECRET.");
    if (authorizationPrivateKey === undefined) {
      problems.push(
        "Live mode requires the app's authorization key as PRIVY_AUTHORIZATION_PRIVATE_KEY " +
          "(or PRIVY_AUTHORIZATION_KEY): the additional signer that Privy lets sign the pull under the policy.",
      );
    }
    if (
      appId !== undefined &&
      appSecret !== undefined &&
      authorizationPrivateKey !== undefined &&
      signerId !== undefined &&
      signerId !== ""
    ) {
      privy = guarded({ appId, appSecret, authorizationPrivateKey, signerId }, () => ({
        appId,
        appSecret: "<redacted:privyAppSecret>",
        authorizationPrivateKey: "<redacted:privyAuthorizationKey>",
        signerId,
      }));
    }
  } else {
    // Delete by NAME. `hasOwnProperty` and `delete` do not invoke a getter, so
    // the values never enter this process — which is what "never reads secrets
    // outside live mode" means, and what the test with a throwing getter proves.
    const present = SECRET_VARS.filter((name) => Object.prototype.hasOwnProperty.call(env, name));
    for (const name of SECRET_VARS) delete env[name];
    if (present.length > 0) {
      warnings.push(
        `${present.join(", ")}: present in the environment (value not inspected, possibly empty) and removed unread. ` +
          "Dry run holds no secret; set SIP_WORKER_ALLOW_BROADCAST to the exact sentence to arm.",
      );
    }
  }

  // --- the sweep ---------------------------------------------------------------
  //
  // The part that catches the accident this file cannot otherwise see: a
  // 0x+64-hex value is registered no matter WHICH variable it arrived in, so a
  // signing key pasted into SIP_VAULT_FACTORY is redacted from every subsequent
  // log line with a label naming the variable to rotate. It runs AFTER the
  // secret variables are gone, so in dry run the attester key's own variable is
  // never read even by the sweep.
  for (const [name, value] of Object.entries(env)) {
    if (value === undefined) continue;
    const trimmed = value.trim();
    if (PRIVATE_KEY.test(trimmed)) redactor.register(trimmed, `possible-key:${name}`);
  }

  // --- RPC ---------------------------------------------------------------------
  //
  // One list, preferred first (DESIGN.md §2: "RPC URL list split on commas").
  // Each entry is registered the moment it is read, not at the end: a URL
  // carries the API key and the next few lines can already fail.
  const rpcRaw = first(env, ["SIP_RPC_URLS", "SIP_RPC_URL"]);
  const rpcUrls: string[] = [];
  if (rpcRaw === undefined) {
    problems.push("SIP_RPC_URLS is required: one or more http(s) JSON-RPC endpoints, comma-separated, preferred first.");
  } else {
    const entries = rpcRaw
      .split(",")
      .map((part) => part.trim())
      .filter((part) => part !== "");
    if (entries.length === 0) problems.push("SIP_RPC_URLS holds no endpoint, only commas or whitespace.");
    entries.forEach((entry, index) => {
      redactor.register(entry, `rpcUrl:${index}`);
      let parsed: URL | null;
      try {
        parsed = new URL(entry);
      } catch {
        parsed = null;
      }
      if (parsed === null || (parsed.protocol !== "http:" && parsed.protocol !== "https:")) {
        problems.push(`SIP_RPC_URLS entry #${index + 1} is not an http(s) URL: it holds ${shape(entry)}.`);
      } else {
        rpcUrls.push(entry);
      }
    });
  }

  // --- storage -----------------------------------------------------------------
  const databaseUrlRaw = first(env, ["DATABASE_URL", "SIP_DATABASE_URL"]);
  let databaseUrl: string | null = null;
  if (databaseUrlRaw !== undefined) {
    // Registered before anything can fail: the URL carries the database password.
    redactor.register(databaseUrlRaw, "databaseUrl");
    let parsed: URL | null;
    try {
      parsed = new URL(databaseUrlRaw);
    } catch {
      parsed = null;
    }
    if (parsed === null || (parsed.protocol !== "postgres:" && parsed.protocol !== "postgresql:")) {
      problems.push(`DATABASE_URL must be a postgres:// URL, got ${shape(databaseUrlRaw)}.`);
    } else if (parsed.port === "6543") {
      // Supabase's transaction pooler (6543) does not keep a session, and
      // pg_advisory_lock is session scoped — it would appear to be granted and
      // hold nothing, so two workers would run believing they were alone.
      // Refused here rather than discovered as a duplicate pull later.
      problems.push(
        "DATABASE_URL points at port 6543, the transaction pooler. Advisory locks are session " +
          "scoped and do not survive it, so two workers could run at once. Use the session pooler on port 5432.",
      );
    } else {
      databaseUrl = databaseUrlRaw;
    }
  } else if (mode === "live") {
    // Tightening beyond DESIGN.md §2, which only says "null ⇒ memory ledger":
    // the memory ledger is for tests and dry runs. A live worker that forgets a
    // SENT pull across a restart can attest the same window again under a fresh
    // nonce, and Phase 0's executor would accept it.
    problems.push(
      "Live mode requires DATABASE_URL: the memory ledger forgets every INTENT and SENT pull on restart, " +
        "and a forgotten pull is a window pulled twice.",
    );
  }

  // --- chain -------------------------------------------------------------------
  const chainId = positiveInteger(first(env, ["SIP_CHAIN_ID"]), CHAIN_ID, "SIP_CHAIN_ID", problems);
  const factory = requiredAddress(first(env, ["SIP_VAULT_FACTORY"]), "SIP_VAULT_FACTORY", problems);
  const executor = requiredAddress(first(env, ["SIP_SETTLEMENT_EXECUTOR"]), "SIP_SETTLEMENT_EXECUTOR", problems);
  const logsFromBlock = requiredBlock(first(env, ["SIP_LOGS_FROM_BLOCK"]), "SIP_LOGS_FROM_BLOCK", problems);

  // --- tuning ------------------------------------------------------------------
  const pollMs = positiveInteger(first(env, ["SIP_POLL_MS"]), DEFAULTS.pollMs, "SIP_POLL_MS", problems);
  const finalityMarginL2 = nonNegativeBigInt(
    first(env, ["SIP_FINALITY_MARGIN_L2"]),
    DEFAULTS.finalityMarginL2,
    "SIP_FINALITY_MARGIN_L2",
    problems,
  );
  const maxLogSpan = nonNegativeBigInt(first(env, ["SIP_MAX_LOG_SPAN"]), DEFAULTS.maxLogSpan, "SIP_MAX_LOG_SPAN", problems);
  if (maxLogSpan === 0n) problems.push("SIP_MAX_LOG_SPAN must be at least 1: a zero-width eth_getLogs chunk scans nothing forever.");

  // Scrubbed on the way out. Nothing above interpolates a value into a message —
  // that is the actual fix — and this is the guarantee that stays true if someone
  // later forgets, because bin/worker.mts writes these straight to stderr before
  // any logger exists.
  const scrub = (text: string): string => redactor.scrub(text);
  if (problems.length > 0) return { ok: false, problems: problems.map(scrub), redactor };

  const config: WorkerConfig = {
    mode,
    chainId,
    rpcUrls,
    factory,
    executor,
    logsFromBlock,
    databaseUrl,
    pollMs,
    finalityMarginL2,
    maxLogSpan,
    attesterPrivateKey,
    privy,
  };
  return { ok: true, config: guarded(config, () => describeConfig(config)), warnings: warnings.map(scrub), redactor };
}

/**
 * Reads process.env once; dry run by default; live only with the byte-exact
 * sentinel; never reads secrets outside live mode. Throws `ConfigError` (with
 * scrubbed `problems`) rather than returning a config that "probably works".
 */
export function loadConfig(env: NodeJS.ProcessEnv, options: LoadConfigOptions = {}): WorkerConfig {
  const result = parseConfig(env, options.redactor);
  if (!result.ok) throw new ConfigError(result.problems);
  const warn =
    options.onWarning ??
    ((message: string): void => {
      process.stderr.write(`warning: ${message}\n`);
    });
  for (const warning of result.warnings) warn(warning);
  return result.config;
}
