[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sip_vault = "7rtgXTu852M1NTx7PLoJd3bChaCb2hgsgv5o54aFv6Fy"
toy_venue = "8sa7DUWmKVerygiUKhaSxzE6f7cigiE4mb7Q7WEKeiq8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha --import=tsx -t 1000000 \"tests/**/*.ts\""
