// What both local proofs need: throwaway wallets that sign like Privy's, the
// waits a validator asks for, one read-only look at mainnet, and a relay that
// COUNTS what the web asks Solana for.
//
// Extracted from vault-local.local.test.ts so the live proof uses the very same
// helpers rather than a second copy: two copies of "wait until it landed" is how
// one proof starts passing for a reason the other would have caught.
//
// Every key here is generated by the caller. Nothing reads the operator's.

import { createPrivateKey, sign } from "node:crypto";
import { createServer, type Server } from "node:http";

import { LIGHTHOUSE_PROGRAM, base64Encode, tryBase64Decode, TOKEN_2022_PROGRAM } from "@sip/solana-core/client";
import { Keypair, PublicKey, Transaction, TransactionInstruction, TransactionMessage, VersionedTransaction, type Connection, type VersionedTransactionResponse } from "@solana/web3.js";
import { expect } from "vitest";

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));

/** What a wallet's signMessage returns, with node:crypto. */
export function signBytes(signer: Keypair, message: Uint8Array): Uint8Array {
  const privateKey = createPrivateKey({
    key: { kty: "OKP", crv: "Ed25519", d: Buffer.from(signer.secretKey.subarray(0, 32)).toString("base64url"), x: Buffer.from(signer.publicKey.toBytes()).toString("base64url") },
    format: "jwk",
  });
  return Uint8Array.from(sign(null, message, privateKey));
}

/** What a wallet's signTransaction returns: its own slot signed over the bytes it was given. */
export function signWith(bytes: Uint8Array, signer: Keypair): Uint8Array {
  const tx = VersionedTransaction.deserialize(bytes);
  tx.sign([signer]);
  return Uint8Array.from(tx.serialize());
}

const u64le = (value: bigint): number[] => {
  const bytes = new Uint8Array(8);
  new DataView(bytes.buffer).setBigUint64(0, value, true);
  return [...bytes];
};

/**
 * Lighthouse checks in the byte shapes Phantom adds on mainnet (log level 4;
 * packages/solana-core/test/phantom-rewrite.ts cites the transactions they were
 * decoded from), with the proof's own bounds.
 */
export const PHANTOM_CHECK = {
  /** AssertAccountInfoMulti [Lamports >= min, KnownOwner == System, DataLength == 0]: Phantom's check on the fee payer. */
  payer: (minLamports: bigint): number[] => [6, 4, 3, 0, ...u64le(minLamports), 4, 3, 0, 0, 1, ...u64le(0n), 0],
  /** AssertAccountInfoMulti [KnownOwner == System, DataLength == 0]. */
  system: (): number[] => [6, 4, 2, 3, 0, 0, 1, ...u64le(0n), 0],
  /** AssertAccountInfoMulti [Owner == program]. */
  owner: (program: string): number[] => [6, 4, 1, 2, ...new PublicKey(program).toBytes(), 0],
  /** AssertTokenAccountMulti [Delegate == None, DelegatedAmount <= 0, TokenAccountOwnerIsDerived]. */
  tokenAccount: (): number[] => [10, 4, 3, 3, 0, 0, 6, ...u64le(0n), 5, 8],
};

/** A Lighthouse instruction checking `account`, named read-only and unsigned, as Phantom names it. */
export const lighthouseCheck = (data: readonly number[], account: string): TransactionInstruction =>
  new TransactionInstruction({ programId: new PublicKey(LIGHTHOUSE_PROGRAM), keys: [{ pubkey: new PublicKey(account), isSigner: false, isWritable: false }], data: Buffer.from(data) });

/**
 * Phantom as it signs on mainnet, replaced: `checks` (read when Phantom is asked)
 * appended after every instruction it was given, the message compiled again,
 * the pension key's slot signed. Every call recorded.
 */
export function phantomOnMainnet(owner: Keypair, checks: () => Promise<readonly TransactionInstruction[]>) {
  const calls = { pensionIn: [] as Uint8Array[], pensionOut: [] as Uint8Array[] };
  return {
    calls,
    pension: {
      signWithPension: async (bytes: Uint8Array) => {
        calls.pensionIn.push(bytes);
        const message = TransactionMessage.decompile(VersionedTransaction.deserialize(bytes).message);
        message.instructions.push(...(await checks()));
        const tx = new VersionedTransaction(message.compileToLegacyMessage());
        tx.sign([owner]);
        const signed = Uint8Array.from(tx.serialize());
        calls.pensionOut.push(signed);
        return signed;
      },
    },
  };
}

/** Privy, replaced: a pension key and a trading wallet as Keypairs, every call recorded. */
export function wallets(owner: Keypair, trading: Keypair) {
  const calls = { order: [] as string[], consent: [] as Uint8Array[], consentSigned: [] as Uint8Array[], pensionIn: [] as Uint8Array[], pensionOut: [] as Uint8Array[], tradingIn: [] as Uint8Array[] };
  return {
    calls,
    pension: {
      signWithPension: async (bytes: Uint8Array) => {
        calls.order.push("pension");
        calls.pensionIn.push(bytes);
        const signed = signWith(bytes, owner);
        calls.pensionOut.push(signed);
        return signed;
      },
    },
    trading: {
      signMessageWithTrading: async (message: Uint8Array) => {
        calls.order.push("consent");
        calls.consent.push(message);
        const signature = signBytes(trading, message);
        calls.consentSigned.push(signature);
        return signature;
      },
      signWithTrading: async (bytes: Uint8Array) => {
        calls.order.push("trading");
        calls.tradingIn.push(bytes);
        return signWith(bytes, trading);
      },
    },
  };
}

const CONFIRM_TIMEOUT_MS = 60_000;
const MAINNET_RPC = "https://api.mainnet-beta.solana.com";

export interface ProofChain {
  confirmed(signature: string): Promise<void>;
  landed(signature: string): Promise<VersionedTransactionResponse>;
  airdrop(to: PublicKey, amount: bigint): Promise<void>;
  /** Sends signed bytes straight to the validator, past the web's relay, and waits for them to land. */
  direct(transaction: Transaction, ...signers: Keypair[]): Promise<VersionedTransactionResponse>;
}

/**
 * The waits a validator asks for, bound to a connection the caller opens later
 * (a getter, because the validator starts in beforeAll).
 */
export function createProofChain(getConnection: () => Connection): ProofChain {
  const confirmed = async (signature: string): Promise<void> => {
    const connection = getConnection();
    const deadline = Date.now() + CONFIRM_TIMEOUT_MS;
    for (;;) {
      const [status] = (await connection.getSignatureStatuses([signature])).value;
      if (status?.err) throw new Error(`${signature} failed: ${JSON.stringify(status.err)}`);
      if (status?.confirmationStatus === "confirmed" || status?.confirmationStatus === "finalized") return;
      if (Date.now() > deadline) throw new Error(`${signature} was not confirmed within ${CONFIRM_TIMEOUT_MS / 1_000} s`);
      await sleep(250);
    }
  };

  const landed = async (signature: string): Promise<VersionedTransactionResponse> => {
    await confirmed(signature);
    const connection = getConnection();
    for (let attempt = 0; attempt < 40; attempt++) {
      const tx = await connection.getTransaction(signature, { commitment: "confirmed", maxSupportedTransactionVersion: 0 });
      if (tx !== null) {
        expect(tx.meta?.err ?? null).toBeNull();
        return tx;
      }
      await sleep(250);
    }
    throw new Error(`${signature} could not be read back`);
  };

  const airdrop = async (to: PublicKey, amount: bigint): Promise<void> => {
    let lastError: unknown = null;
    for (let attempt = 0; attempt < 10; attempt++) {
      try {
        await confirmed(await getConnection().requestAirdrop(to, Number(amount)));
        return;
      } catch (error) {
        // The faucet answers a moment after the RPC does.
        lastError = error;
        await sleep(1_000);
      }
    }
    throw new Error(`the faucet did not fund ${to.toBase58()}: ${String(lastError)}`);
  };

  const direct = async (transaction: Transaction, ...signers: Keypair[]): Promise<VersionedTransactionResponse> => {
    const connection = getConnection();
    const recent = await connection.getLatestBlockhash("confirmed");
    transaction.recentBlockhash = recent.blockhash;
    transaction.feePayer = signers[0]!.publicKey;
    transaction.sign(...signers);
    return landed(await connection.sendRawTransaction(transaction.serialize(), { skipPreflight: false }));
  };

  return { confirmed, landed, airdrop, direct };
}

/** The SPYx/USDC pool's SPYx vault on mainnet: a Token-2022 account with SPYx's account extensions, 175 bytes. */
export const SPYX_TEMPLATE_ACCOUNT = "CiQuPAfYp5v82vijk6u7wqFnaZqtGdJfUUSjDKAtT9ML";

/** One read-only getAccountInfo from mainnet's public RPC, retried once if it throttles. */
export async function mainnetAccountBytes(address: string): Promise<{ owner: string; data: Uint8Array }> {
  for (let attempt = 0; ; attempt++) {
    const response = await fetch(MAINNET_RPC, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "getAccountInfo", params: [address, { encoding: "base64", commitment: "confirmed" }] }),
    });
    if (response.status === 429 && attempt === 0) {
      await sleep(5_000);
      continue;
    }
    const body = (await response.json()) as { result?: { value?: { owner?: string; data?: [string, string] } | null } };
    const value = body.result?.value;
    const data = tryBase64Decode(value?.data?.[0] ?? "");
    if (value?.owner === undefined || data === null) throw new Error(`mainnet did not answer the account ${address} (HTTP ${response.status})`);
    return { owner: value.owner, data };
  }
}

/** An account preloaded at genesis with --account. */
export interface PreloadedAccountJson {
  readonly pubkey: string;
  readonly json: unknown;
}

/**
 * A SPYx holding for `vault`, at `at`: the mainnet template's bytes with the
 * owner replaced and the amount set, and no delegate or close authority.
 *
 * WHY A COPY. No SPYx mint or freeze authority exists locally, and SPYx is a
 * Token-2022 mint with extensions a hand-built account would not carry — so the
 * proof copies a real one, read once, read-only.
 */
export async function spyxHoldingAccount(options: { vault: PublicKey; at: PublicKey; amountRaw: bigint }): Promise<PreloadedAccountJson> {
  const template = await mainnetAccountBytes(SPYX_TEMPLATE_ACCOUNT);
  if (template.owner !== TOKEN_2022_PROGRAM || template.data.length !== 175 || template.data[165] !== 2 || template.data[108] !== 1) {
    throw new Error("the SPYx template account is no longer an initialized 175-byte Token-2022 account");
  }
  const data = template.data.slice();
  data.set(options.vault.toBytes(), 32);
  new DataView(data.buffer).setBigUint64(64, options.amountRaw, true);
  data[72] = 0; // delegate: none
  data[129] = 0; // close authority: none
  const pubkey = options.at.toBase58();
  return { pubkey, json: { pubkey, account: { lamports: 10_000_000, data: [base64Encode(data), "base64"], owner: TOKEN_2022_PROGRAM, executable: false, rentEpoch: 0, space: 175 } } };
}

// ── the counting relay ───────────────────────────────────────────────────────

/** One upstream POST the web made, and the JSON-RPC methods inside it. */
export interface RelayCall {
  readonly batch: boolean;
  readonly methods: readonly string[];
}

export interface CountingRelay {
  readonly url: string;
  /** Every upstream POST since the last reset, in order. */
  calls(): readonly RelayCall[];
  reset(): void;
  stop(): Promise<{ readonly stopped: boolean; readonly portRefused: boolean }>;
}

/**
 * A relay between the web and the validator that COUNTS.
 *
 * The rate plan is a promise about how much the dashboard asks Solana for — one
 * batch for a snapshot, one call plus one batch for a page of history. Asserting
 * that from inside the web would only prove the web agrees with itself; this
 * counts the requests that actually left it.
 */
export async function startCountingRelay(options: { readonly upstream: string; readonly port: number }): Promise<CountingRelay> {
  const seen: RelayCall[] = [];

  const server: Server = createServer((request, response) => {
    const chunks: Buffer[] = [];
    request.on("data", (chunk: Buffer) => chunks.push(chunk));
    request.on("end", () => {
      void (async () => {
        const text = Buffer.concat(chunks).toString("utf8");
        try {
          const body = JSON.parse(text) as { method?: string } | { method?: string }[];
          const batch = Array.isArray(body);
          seen.push({ batch, methods: (batch ? body : [body]).map((member) => String(member?.method)) });
        } catch {
          seen.push({ batch: false, methods: ["<unparseable>"] });
        }
        try {
          const upstream = await fetch(options.upstream, { method: "POST", headers: { "content-type": "application/json" }, body: text });
          const answer = await upstream.text();
          response.writeHead(upstream.status, { "content-type": "application/json" });
          response.end(answer);
        } catch (error) {
          response.writeHead(502, { "content-type": "application/json" });
          response.end(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32_603, message: String(error) } }));
        }
      })();
    });
  });

  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen({ host: "127.0.0.1", port: options.port, exclusive: true }, () => resolve());
  });

  return {
    url: `http://127.0.0.1:${options.port}`,
    calls: () => seen,
    reset: () => {
      seen.length = 0;
    },
    stop: async () => {
      await new Promise<void>((resolve) => server.close(() => resolve()));
      const { portRefused } = await import("./web-server");
      return { stopped: true, portRefused: await portRefused(options.port) };
    },
  };
}
