/**
 * Proves that src/chain.ts still describes the settle() the contracts actually
 * compile to.
 *
 * Run: pnpm run check:selector   (also the first half of `pnpm test`)
 *
 * WHY THIS EXISTS.
 *
 * classify.ts recognises a settlement by four bytes:
 *
 *     input.startsWith(SETTLE_SELECTOR)
 *
 * `startsWith` has no failure mode. When the selector moves and the constant
 * does not, nothing throws, nothing logs, and no test that does not already
 * contain a settlement notices. The transaction stops being a SETTLEMENT, and
 * the contribution — which is the protocol paying the user's own vault — stops
 * being added back as an external withdrawal. Every window containing a
 * settlement is then wrong, in the direction of understating profit.
 *
 * The selector moves for reasons that look harmless in Solidity: settle() takes
 * the whole SettlementAttestation struct, so ADDING A FIELD to that struct
 * changes the signature. Promoting startBlockL2/endBlockL2 from ledgerRoot
 * payload to real attestation fields did exactly that (0xf38ac34f -> 0xc8f2629d)
 * without one line of settle() itself changing.
 *
 * So: read the truth from the compiled ABI, never from a second copy of the
 * literal. @nuvem/contracts-artifacts is generated by `forge build` and is
 * itself kept honest by its own scripts/check-dist-fresh.mjs.
 *
 * This guard is deliberately NOT skippable the way check-dist-fresh.mjs is. That
 * script skips when Foundry is absent because it must re-derive dist/ from
 * source; this one only reads the committed dist/, which is present in every
 * clone and in the container.
 */

import { abis, selectors } from "@nuvem/contracts-artifacts";

import * as chain from "../src/chain.js";

// Widened deliberately. chain.ts declares these `as const`, so TypeScript knows
// each literal exactly and reports every comparison below as provably-false —
// which is precisely backwards: their whole purpose is to fail after somebody
// edits those literals. A guard the compiler can constant-fold is not a guard.
const SETTLE_SELECTOR: string = chain.SETTLE_SELECTOR;
const LEGACY_SETTLE_SELECTORS: readonly string[] = chain.LEGACY_SETTLE_SELECTORS;
const SETTLE_SELECTORS: readonly string[] = chain.SETTLE_SELECTORS;
const SETTLEMENT_EXECUTORS: readonly string[] = chain.SETTLEMENT_EXECUTORS;

type AbiParam = { readonly type: string; readonly name?: string; readonly components?: readonly AbiParam[] };
type AbiEntry = { readonly type: string; readonly name?: string; readonly inputs?: readonly AbiParam[] };

const failures: string[] = [];
const checks: string[] = [];

const executorFunctions = selectors.SettlementExecutor.functions;
const settleEntries = Object.entries(executorFunctions).filter(([signature]) => signature.startsWith("settle("));

// ---------------------------------------------------------------------------
// 1. The current selector
// ---------------------------------------------------------------------------
if (settleEntries.length !== 1) {
  failures.push(
    `SettlementExecutor publishes ${settleEntries.length} settle() overloads ` +
      `(${settleEntries.map(([signature]) => signature).join(", ") || "none"}). ` +
      "chain.ts assumes exactly one, because classification matches on four bytes and " +
      "cannot choose between two shapes.",
  );
} else {
  const [signature, artifactSelector] = settleEntries[0]!;
  checks.push(`settle signature: ${signature}`);
  if (artifactSelector !== SETTLE_SELECTOR) {
    failures.push(
      `SETTLE_SELECTOR is stale.\n` +
        `      chain.ts:  ${SETTLE_SELECTOR}\n` +
        `      contracts: ${artifactSelector}  (${signature})\n` +
        `      Until this is corrected, classify.ts sees no settlement transactions at all:\n` +
        `      the contribution reads as an opaque cash outflow and every window containing\n` +
        `      one is refused, or worse, silently mis-summed.`,
    );
  } else {
    checks.push(`SETTLE_SELECTOR ${SETTLE_SELECTOR} matches the compiled ABI`);
  }
}

// ---------------------------------------------------------------------------
// 2. The historical selectors
// ---------------------------------------------------------------------------
//
// These must stay: the engine reconstructs windows that already happened, and
// mainnet settlement 0xd342d117…cad186 carries 0xf38ac34f. But a legacy entry
// that equals the CURRENT selector means someone appended instead of replacing,
// and a legacy entry that is still compiled means the redeploy did not actually
// change the shape it claims to have changed.
const compiledSelectors = new Set(Object.values(executorFunctions));
for (const legacy of LEGACY_SETTLE_SELECTORS) {
  if (!/^0x[0-9a-f]{8}$/.test(legacy)) {
    failures.push(`LEGACY_SETTLE_SELECTORS entry ${legacy} is not a lowercase 4-byte selector.`);
    continue;
  }
  if (legacy === SETTLE_SELECTOR) {
    failures.push(
      `${legacy} is listed as legacy AND as current. One of the two was edited without the other.`,
    );
    continue;
  }
  if (compiledSelectors.has(legacy as `0x${string}`)) {
    failures.push(
      `${legacy} is listed as a superseded settle() selector but is still present in the ` +
        `compiled SettlementExecutor ABI. History and the current build cannot both own it.`,
    );
  }
}
checks.push(`${LEGACY_SETTLE_SELECTORS.length} historical selector(s) retained for chain history`);

if (new Set(SETTLE_SELECTORS).size !== SETTLE_SELECTORS.length) {
  failures.push(`SETTLE_SELECTORS contains duplicates: ${SETTLE_SELECTORS.join(", ")}`);
}

// ---------------------------------------------------------------------------
// 3. The L2 fields the whole redeploy exists for
// ---------------------------------------------------------------------------
//
// A matching selector proves the two sides agree on a shape; it does not prove
// which shape. The engine reports startBlockL2/endBlockL2 and the keeper signs
// them, and that is only meaningful if the attestation still carries them as
// real fields. If they were reverted back into ledgerRoot the selector would
// move and check 1 would fire — but it would fire as "update the constant",
// which is precisely the wrong instruction. Name the cause here instead.
const settleFragment = (abis.SettlementExecutor as unknown as readonly AbiEntry[]).find(
  (entry) => entry.type === "function" && entry.name === "settle",
);
const attestationFields = (settleFragment?.inputs?.[0]?.components ?? []).map((component) => component.name);
for (const required of ["startBlock", "endBlock", "startBlockL2", "endBlockL2"] as const) {
  if (!attestationFields.includes(required)) {
    failures.push(
      `SettlementAttestation has no \`${required}\` field. Present fields: ` +
        `${attestationFields.join(", ") || "(none)"}.\n` +
        `      Settlement progression is enforced on the L2 pair; the L1 pair is what the\n` +
        `      contract compares against block.number. The engine produces both and cannot\n` +
        `      attest against a struct that has dropped either.`,
    );
  }
}
checks.push(`SettlementAttestation carries ${attestationFields.length} fields including the L1 and L2 ranges`);

// ---------------------------------------------------------------------------
// 4. What this guard cannot check, said out loud
// ---------------------------------------------------------------------------
//
// SETTLEMENT_EXECUTORS is addresses, and the artifacts package deliberately
// publishes no deployment data (its own test asserts index.deployments is
// undefined). So nothing here can tell whether the list is current. All that is
// verifiable is shape.
for (const executor of SETTLEMENT_EXECUTORS) {
  if (!/^0x[0-9a-f]{40}$/.test(executor)) {
    failures.push(`SETTLEMENT_EXECUTORS entry ${executor} is not a lowercase 20-byte address.`);
  }
}
if (SETTLEMENT_EXECUTORS.length === 0) {
  failures.push("SETTLEMENT_EXECUTORS is empty; no transaction could ever classify as a settlement.");
}

if (failures.length > 0) {
  console.error(`[session-engine] settle selector drift (${failures.length}):`);
  for (const failure of failures) console.error(`  - ${failure}`);
  console.error(
    "\nFix by re-reading the value from @nuvem/contracts-artifacts " +
      "(pnpm --dir packages/contracts-artifacts run build first), then updating " +
      "packages/session-engine-old/src/chain.ts. Never relax this check: the bug it " +
      "prevents does not produce an error, it produces wrong numbers.",
  );
  process.exit(1);
}

console.log(`[session-engine] settle selector check passed:`);
for (const check of checks) console.log(`  - ${check}`);
